### ISSUE TITLE
Prismo

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#1]
Just saw your repo in my github feed. Are you aware that theres already a project which is doing basically the same thing? Plus its almost production ready.

https://gitlab.com/mbajur/prismo

https://prismo.news/

**Comment by wakest** [comment]
came here to mention Prismo as well! Also I am pretty sure [lobste.rs](http://lobste.rs/)  said they are interested in adding ActivityPub.

**Comment by dessalines** [comment]
I'll check it out, looks cool. doesn't seem to have the concept of subs / communities, just tags. Too bad I can't sign up for either of them :(

**Comment by Nutomic** [comment]
They are adding that now (or something similar). 

https://socialhub.network/t/use-moderated-tags-instead-of-subprismos/370

For Prismo you need to donate if you want to sign up, but afaik they will go public soon. You could also try to ask the dev nicely to let you sign up, eg on [Matrix](https://riot.im/app/#/room/#prismo:matrix.org).

**Comment by wakest** [comment]
I have an account on prismo if any of yall want me to test anything. you can just donate 1$ to get one as well.

**Comment by dessalines** [comment]
I see that prismo is using rails too... wouldn't it be valuable to write another implementation in rust anyway?

**Comment by wakest** [comment]
@dessalines there is already a AP server written in rust you could start with called [rustodon](https://github.com/rustodon/rustodon)!

**Comment by Nutomic** [comment]
FYI signups on the main Prismo instane were opened today. And full federation import should be in the next version.

https://prismo.news/posts/300
