### ISSUE TITLE
Publish official docker image in docker hub

### ISSUE THREAD

**Issue by miki725** [dessalines/lemmy#101]
Would be useful to publish official image to docker hub to make testing easier vs having a need to pull the repo down. Thoughts?

Found https://hub.docker.com/r/alchemyjones/lemmy  but does not look like it's an official image. Readme, etc are missing.

**Comment by dessalines** [comment]
Hrm... I'm currently using a docker-compose file, which does a complete build and install of the project, and sets up a postgres db. 

I'm guessing pushing the docker image to dockerhub would make it so users don't have to do the build step, and then the docker-compose file would just reference the postgres image, and the lemmy image. 

I'd be reticent to do it right now at least for a few reasons:
- I'm doing builds almost every day, and those images are pretty large. I live in the US too so my data cap of 1 TB / month doesn't help.
- After the initial build, I set up caching correctly for everything in the dockerfile, so now just running `./docker_update.sh` will update your running lemmy instance in a few seconds. So pulling a new 700 MB image is far worse than an incremental update like already works.
- Dockerhub is a paid service, not sure how much it'll cost me.

If later on ppl really want it, and can help me set up a docker-compose for the dockerhub version, I'd be willing to.

**Comment by dessalines** [comment]
Here's a poll on whether to do this: https://simplevote.tk/#/poll/rkpB

**Comment by miki725** [comment]
thanks for the response. everything you mentioned makes complete sense. just some background about the request:

having the image in docker hub might make things simpler for some people to test depending on how they do deployments assuming they wish to deploy outside of their laptop/dev environment. for example in [portainer](https://www.portainer.io) it is trivial to start existing image container. then you can simply pull new images whenever ready (assuming people either dont have a cap or are ok using it to download new image)

also docker hub is free for open-source projects. you can even setup an automated build so as soon as you push, docker will build the image for you. no need to do anything on your part except setting up docker hub automated build. you can leave the repo as is and locally continue using `update_docker.sh`. should be no impact to existing workflow

**Comment by chovy** [comment]
I would appreciate this. I am having difficulty running two intances on same server.

**Comment by dessalines** [comment]
This is in the pipe.

**Comment by dessalines** [comment]
Here's the official image now, and instruction are in the readme for this too now.

https://cloud.docker.com/repository/docker/dessalines/lemmy/general
