### ISSUE TITLE
Add "mark all as read" button in inbox

### ISSUE THREAD

**Issue by mister-monster** [dessalines/lemmy#107]
Currently each message must be marked as read independently. This is fine for testing, but as the userbase grows this may become unwieldy for users. Users will need a way to mark all inbox notifications as read.

**Comment by poVoq** [comment]
Would it be possible to add a function to mark topics as read automatically? Right now I have to mark them as read manually each time.

**Comment by dessalines** [comment]
topics? lemmy doesn't have topics, it has comment replies, mentions, and private messages.

**Comment by poVoq** [comment]
What ever they are called :) If I visit a thread and read the OP or comment, it still remains in the notification section until I manually press the mark as read button.

**Comment by dessalines** [comment]
I have it so that if you click the link from the inbox, it marks it as read, but otherwise I have no way of knowing which comments are "read", unless I implement some kind of scroll-linked thing that marks off as read anything in your view.

**Comment by poVoq** [comment]
Hmm, I think the main annoyance I have comes from the fact that if I visit a thread from the main feed it does not get marked as read in the notifications. 

I don't think it actually needs to be scroll linked, just opening the thread from anywhere should mark mark any current comments as read.

**Comment by Nutomic** [comment]
@poVoq That would work for now as most threads are quite small, but it will be very counterproductive once we get threads with dozens or hundreds of comments.

**Comment by dessalines** [comment]
I also think its a bad idea to mark comments read when not explicitly viewed or clicked as read. You might have wanted to respond to one comment later, and prefer for it to be unread until then.

**Comment by poVoq** [comment]
Maybe it could be an opt-in user setting? Having all these unread message notifications when in fact having read all of them already is highly unintuitive and not how other platforms manage it.
