### ISSUE TITLE
pre-fetch title when submitting a url

### ISSUE THREAD

**Issue by chovy** [dessalines/lemmy#112]
It would be nice to grab the title of a link automatically like how reddit does. Saves time

**Comment by dessalines** [comment]
Does anyone know a js library that can do this? I don't want to do this in the back end.

**Comment by pojntfx** [comment]
[Metascraper](https://github.com/microlinkhq/metascraper) could do this. One possible usage:

[![Edit lxwlm046om](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lxwlm046om?fontsize=14)

**Comment by chovy** [comment]
You will probably have to use puppeteer on the backend to crawl SPAs.

**Comment by chovy** [comment]
This doesn't work for javascript apps. Youtube title doesn't work.

**Comment by dessalines** [comment]
That has to do with the server this is using, https://textance.herokuapp.com/title/${url} . If you can find another that's better let me know, but I don't want anything in the back end related to this, it must be a front end only solution.
