### ISSUE TITLE
need abiility to add tracking code

### ISSUE THREAD

**Issue by chovy** [dessalines/lemmy#115]
ie: google adsense tracking code or clicky.com

need a form to enter a tracking code

**Comment by mister-monster** [comment]
Could you elaborate? Is this a special use case for you or something that a general user would like to do?

**Comment by dessalines** [comment]
No tracking, or ads allowed, ever. This will not spy on user actions in that way.

**Comment by chovy** [comment]
I just add it to index.html -- its a little rediculous to not allow google anlytics or mix panel.

**Comment by AidenY69** [comment]
> I just add it to index.html -- its a little rediculous to not allow google anlytics or mix panel.

is this still workable? where is that index.html file?

**Comment by Nutomic** [comment]
You can set `LEMMY_UI_CUSTOM_HTML_HEADER`
