### ISSUE TITLE
add rss feed for forums

### ISSUE THREAD

**Issue by chovy** [dessalines/lemmy#118]
WOuld be nice to get an rss feed of forums so I can cross promote to twitter, etc.

**Comment by dessalines** [comment]
Makes sense, I've never messed with rss feeds so I might need some help with this one.

**Comment by chovy** [comment]
i'm not sure what your backend is, but you would need a json to xml module and then you can create the rss format which is just xml.

**Comment by adevore** [comment]
I'm volunteering to take on this issue.

**Comment by dessalines** [comment]
Sweet! lemme know if you need any assistance or have any questions. I don't know too much about rss, but can easily wire up the UI side of it if the server side is done.

**Comment by adevore** [comment]
I did some research and it looks like Atom is the better feed format to target. It is the format that Reddit targets, despite the .rss extension. There is another crate under the rust-syndication project on GitHub to handle Atom with a similar API to the rss crate.

**Comment by mraxilus** [comment]
Would also be nice to have an RSS/Atom feed for the user feed, rather than just individual forums.
