### ISSUE TITLE
DATABASE_URL must be set

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#123]
Getting this when I'm trying to build the dev version (commit 244c1dff0c5fb342cca0a576993b80751f2ff99e). Postgres is installed and setup.

**Comment by dessalines** [comment]
try this: 
`export DATABASE_URL=postgres://rrr:rrr@localhost/rrr`

If it works I'll add it to the readme.

**Comment by Nutomic** [comment]
Yep that works. You could probably put it directly into install.sh. And rename that script to something like compile.sh or run.sh

**Comment by dessalines** [comment]
cool, will do.
