### ISSUE TITLE
No Kubernetes Support

### ISSUE THREAD

**Issue by pojntfx** [dessalines/lemmy#126]
It would be awesome if development would not require Docker specifically, but rather Kubernetes (or any CRI). I'll take a look at implementing a minimal Kubernetes development environment using [Skaffold](https://skaffold.dev) as soon as possible if everyone here consents to it.

**Comment by pojntfx** [comment]
One problem I've run in to so far: Multi-Stage builds don't work in Skaffold for now. As a "solution", I'll probably introduce a flag that disables the serving of the frontend from within the backend and splits these two services into two containers.

**Comment by dessalines** [comment]
Ill merge this no matter what, but the server currently doesnt have any clustering / scaling features. The websockets are one difficulty... It keeps all the websocket connections in memory, and sends messages to ppl that are in the same room. 

The db is another, I havent built any scaling into that either. Thats the point of kubernetes right, to scale up / load balance and all that?

**Comment by pojntfx** [comment]
@dessalines Yes, that's one of it's strong suits, but certainly not the only one. For, tbh, it's mostly convenience; no need for any local compute, although it's still possible with a local Kubernetes cluster (i.e. `k3d`). With Kubernetes/Skaffold, you can simply use `skaffold run` without any scripts etc. and get hot reloading and so on, all inside of Kubernetes.
