### ISSUE TITLE
Add autocomplete for textareas, users and communities . 

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#129]

**Comment by dessalines** [comment]
https://github.com/yuku/textcomplete

https://github.com/avcs06/AutoSuggest

https://github.com/zurb/tribute

**Comment by dessalines** [comment]
For user mentions: use `@`

For community mentions: use `#`

**Comment by PopeRigby** [comment]
Maybe the text should show up as @ and #, and the link can still stay as /c/ and /u/

**Comment by dessalines** [comment]
No, cause the /c/ and /u/ are the correct links. I'm really only using @ and # to trigger the autocomplete, the proper links should look like this.

**Comment by PopeRigby** [comment]
Oh. I thought you were trying to make the frontend (i.e. not the URL) reflect Mastodon with the @s and the #s.

**Comment by dessalines** [comment]
Mastodon uses the @, and # for tags, but reddit (and this which doesn't have tags, but communities), uses /u/ and /r/ or /c/. I like that way better both for URLs, and because it allows for more concepts to be created at the top domain later, rather than having to come up with new symbols every time.

**Comment by PopeRigby** [comment]
I see. That makes sense. 👍
