### ISSUE TITLE
How to deal with the same URL posted to multiple communities.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#131]

**Comment by dessalines** [comment]
When a single URL gets posted, multiple times, to multiple communities, it might be nice to:
- See where else its been posted (IE X-Posts).
- Possibly combine these on your front page visually in some way.
- Create a Cross post this to community X button.

**Comment by mister-monster** [comment]
There is an issue with this, which is that if the same post is posted on two communities on different instances, the options are to not notice, or for every federated instance to request information from every other federated instance about every post made. This would not work well at scale.

**Comment by trosel** [comment]
Pointing out that tags are a possibility. Prismo has a simple solution to spam which is that each post can only use 5 tags maximum.

To be fair though, I think Prismo is designed more to be one instance per community. Whereas Lemmy is designed to be many communities on one instance.

**Comment by mister-monster** [comment]
Yeah, Prismo is more like twitter (or mastodon) with upvoting. Instead of communities you have topics (hashtags).

Lemmy differs in that it is community oriented, not topic oriented.

I think this issue is specifically asking how to automate linking two identical posts posted in two or more separate communities. My point above is that this works on one instance hut could get messy when doing it across many instances.

**Comment by mister-monster** [comment]
So it looks to me like building something like this will involve getting a list of all federated instances and searching them all for identical content, building a specialized search engine essentially.

If search functionality is already on the road map it would probably be best to knock this out with that.

One way to show identical content is for a community mod or instance admin to run a bot that uses that search engine every time a new post happens on the instance or community, and comment with the links it finds.

**Comment by dessalines** [comment]
This could do a simple db search for that same URL link, and show a :
`Also posted to /c/bleh 34 days ago` or whenever.
