### ISSUE TITLE
would be reallly nice to add rss feeds to seed forums

### ISSUE THREAD

**Issue by chovy** [dessalines/lemmy#134]

**Comment by dessalines** [comment]
Dup of #118

**Comment by davidoclubb** [comment]
> Dup of #118

This isn't a duplicate of #118; one suggestion was to get an RSS feed as an output, this request was to be able to use an RSS feed as an input to Lemmy to automatically generate items for discussion (something that would be useful for an instance I am considering creating).

For example, taking an RSS from a reputable news source to publish ~10 news items daily without having to babysit input them.

**Comment by Nutomic** [comment]
This is similar to #119, and my answer is the same. This should be handled by an external tool (bot), not integrated in Lemmy.

**Comment by davidoclubb** [comment]
Thanks @Nutomic , I'll look into it if/when I get my instance up and running 🙌👍
