### ISSUE TITLE
add iOS icon

### ISSUE THREAD

**Issue by chovy** [dessalines/lemmy#135]
need to add an icon so when I add to homescreen I get the logo.

**Comment by dessalines** [comment]
This already has a working svg favicon, that works on all modern browsers. This is an apple bug, not here.

**Comment by chovy** [comment]
you need to add the meta tag.

**Comment by chovy** [comment]
`<link rel=apple-touch-icon href=/apple-touch.png>`

**Comment by dessalines** [comment]
Sounds like a good first PR.

**Comment by chovy** [comment]
ok.
