### ISSUE TITLE
Instance admin dashboard

### ISSUE THREAD

**Issue by mister-monster** [dessalines/lemmy#140]
Currently, all mod and admin actions are additional options within the existing web UI. This is fine for operations like banning users, removing posts, etc.

However there are additional operations an administrator of an instance would need to be able to perform. Some of these might include:

1. Blacklisting other instances (so that users from those instances are banned in all communities on the instance being administrated),

2. Locking registrations,

3. Locking creation of new communities,

4. Possible multimedia support,

5. Taking the instance down for maintenance.

This is not exhaustive, however Administrators will need a bit of additional functionality beyond interacting directly with users.

One of the goals after stable launch is that many people decide to run their own instances. An easy way to administer an instance will go a long way towards encouraging this.

I propose we spec out all the desired functionality that an instance admin might need to run their instance and build a simple, secondary UI separate from the client web UI to function as an admin dashboard for instance admins.

**Comment by dessalines** [comment]
Very good idea, this actually shouldn't be too difficult.

**Comment by mister-monster** [comment]
Alright I think we ought to have a discussion though first about what features are desirable here. Of my above mentioned features, which ones do you think it should include? What features do you think an instance admin should have easy UI access to?

In my opinion, besides the functionality shared with mods (appointing mods, banning users, removing posts) anything additional should be here, and I just think it would work best if we had a clear idea of what that is.

**Comment by dessalines** [comment]
Its okay for the admin panel to be accessed remote, admin actions like removing communities, bans, all that stuff has to happen remote anyway. 

There's two levels of security, one is hiding things on the front end if you're not an admin (which a clever person who knows JS could get around), the other is to validate their logged in user `jwt` token on the back end (which is tamper-proof). Unless they know how to crack [bcrypt](https://en.wikipedia.org/wiki/Bcrypt), or discover the jwt secret, its safe.

**Comment by dessalines** [comment]
Make sure custom rate limits are on here.

**Comment by dessalines** [comment]
I've just added a lot of site configs, and the way to do this now is to click `edit` on the site page. From there you can change the site name, description, enable downvotes, etc. Its basically the admin panel.
