### ISSUE TITLE
node.info support

### ISSUE THREAD

**Issue by sunjam** [dessalines/lemmy#144]
[NodeInfo](http://nodeinfo.diaspora.software/) is an effort to create a standardized way of exposing metadata about a server running one of the distributed social networks. The two key goals are being able to [get better insights into the user base of distributed social networking and the ability to build tools that allow users to choose the best fitting software and server for their needs.](https://the-federation.info/)

[See this example implementation for Wordpress](https://wordpress.org/plugins/nodeinfo/).  This is used by Diaspora, Funkwhale, Friendica, Hubzilla, Pleroma and many other federated services, allowing them to be optionally indexed by sites like https://the-federation.info or [fediverse.network](https://fediverse.network/)

**Comment by mister-monster** [comment]
This might be useful for Issue #131

**Comment by dessalines** [comment]
This stuff is on the backburner for me at least until I get some more federation work done, but I'm happy to accept PRs for it.

**Comment by jaywink** [comment]
Hi, not sure if fixed by dev.lemmy.ml NodeInfo is broken at least: https://dev.lemmy.ml/.well-known/nodeinfo

The href goes to "my_domain".

**Comment by dessalines** [comment]
Ah thanks, this is fixed now.
