### ISSUE TITLE
Create webfinger endpoint

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#149]

**Comment by Nutomic** [comment]
So I implemented webfinger [here](https://yerbamate.dev/dessalines/lemmy/pulls/4), and @teromene expanded my implementation in https://github.com/dessalines/lemmy/pull/369. My implementation only supports discovering communities (as @dessalines wants to focus on that for now). The implementation by @teromene also supports user discovery. 

I already described the problem with that in https://github.com/dessalines/lemmy/pull/369#pullrequestreview-335611666. So to solve that, we could use a different type of url, like this:
```
user: /.well-known/webfinger?resource=acct:felix@lemmy.ml
group: /.well-known/webfinger?resource=group:main@lemmy.ml
```

But the question is if other implementations support this, or if we need to wait for them to implement this. We could also prevent the creation of communities and users with identical names at signup, that would most likely let us avoid this problem.

It would be nice to know if other ActivityPub implementations support some kind of different resource type for webfinger requests, but that probably means digging into the source code, or getting a response from the maintainers.

**Comment by Nutomic** [comment]
Okay I think the best way to solve this dilemma is to figure out what our priority is: do we want other activitypub implementations (eg mastodon or pleroma) to be able to federate with Lemmy, or is it more important that Lemmy instances can federate among themselves? The former is more complicated, and we have to work with other projects to find some kind of standard that works for everyone. The latter would be easier, as we can change everything as needed, and worry about other implementations later.

Personally, I think compatibility between Lemmy instances is more important (and also more realistic in the short term).

**Comment by dessalines** [comment]
> user: /.well-known/webfinger?resource=acct:felix@lemmy.ml
> group: /.well-known/webfinger?resource=group:main@lemmy.ml

I like this a lot. We might as well move forward with group, we can always change that later. If mastodon followed the activitypub actor types [here](https://www.w3.org/TR/activitystreams-core/#actors), then `acct` should really be `person`, but nothing we can do about that now.

> We could also prevent the creation of communities and users with identical names at signup, that would most likely let us avoid this problem.

There's community name uniqueness, and user name uniqueness ( case sensitive, but we have to do a poll on that #328 #341 ), so we should be okay here. Its okay if two instances have similar community names, like `group:memes@lemmy.ml` and `group:memes@other_lemmy.ml`

> do we want other activitypub implementations (eg mastodon or pleroma) to be able to federate with Lemmy, or is it more important that Lemmy instances can federate among themselves?

Federate among themselves (for communities) first, then federate with other platforms. The reason is because all other activitypub services are twitter/FB/youtube clones, based on following people, whereas lemmy should start out as following (or subscribing to) federated communities, like reddit. And also right now, the main thing with lemmy is the frontpage of your subbed communities.

**Eventually**, after following federated communities works, we'll add support for following people, and this means that people's posts (think of a mastodon toot as a self-post to your own user sublemmy), will show up on you front page too. That means federated user follows, and a bridge into mastodon / pleroma / everything else. But I'd like to start with federated community following, since that's what makes this project unique.

**Comment by Nutomic** [comment]
> There's community name uniqueness, and user name uniqueness ( case sensitive, but we have to do a poll on that #328 #341 ), so we should be okay here. Its okay if two instances have similar community names, like group:memes@lemmy.ml and group:memes@other_lemmy.ml

What I mean is that there could be users and communities with the same name, on the same instance. For example, `user:lemmy@example.com` and `group:lemmy@example.com`.

**Comment by dessalines** [comment]
That's pry fine, they're different types anyway.
