### ISSUE TITLE
Please build lemmy with privacy in mind - please make it usable for users who block all JS

### ISSUE THREAD

**Issue by ghost** [dessalines/lemmy#155]
_Please build lemmy with privacy in mind - please make it usable for users who block all JavaScript_

I know that many users block JS for privacy and security reasons, so I think it's important that we consider this while building lemmy. Thanks a bunch!

_p.s. As of right now, you can't use lemmy if you don't turn JS on._

**Comment by dessalines** [comment]
The front end framework is https://github.com/infernojs/inferno , which is what I know and am familiar with. That and I built lemmy to be dynamic first ( ie threads are live updating ), which requires a websocket connection which AFAIK requires JavaScript to send data back and forth. 

The API is open tho, anyone is free to build a non live updating version.

**Comment by Zig-03** [comment]
> Also I cant think of any of the federated alternatives that work without js, certainly not mastodon, plume, etc.

You can actually navigate Mastodon with blocked JS just fine 
You can test it on this instance https://mastodon.social/@Gargron/media

**Comment by dessalines** [comment]
I'm seeing that this might be possible with inferno, its called an isomorphic app: https://infernojs.org/docs/guides/isomorphic
