### ISSUE TITLE
Update README.md with a bit of clarification on how the federation aspect of lemmy will work

### ISSUE THREAD

**Issue by ghost** [dessalines/lemmy#160]
How the federation aspect of lemmy will work? Will there be a 'global database' that will make sure all 'subreddit' (how are they called on lemmy?) names are unique? Or each instance will be able to register the same 'subreddit' name and as a result we will have: 
https://dev.lemmy.ml/#/c/asklemmy
https://another.instance/#/c/asklemmy
https://another.instance2/#/c/asklemmy
If it's the latter, then will they aggregate somehow, somewhere? Will it be like on PeerTube where each individual instance has "local videos" and then "all videos"?
So I imagine when visiting https://dev.lemmy.ml/#/c/asklemmy there will be a toggle that will let you choose where you want to take content from: the whole fediverse or only locally?

**Comment by dessalines** [comment]
Its the latter. joining / following communities will be similar to the "remote follow" thing on mastodon, and then those posts will show up in your feed wherever they are.

I'll document this in the readme as I work on federation.

**Comment by LeoPCI** [comment]
Is there any way for people to contribute to federation?

**Comment by apothan** [comment]
Just to clarify, If you followed all three of:
https://dev.lemmy.ml/#/c/asklemmy
https://another.instance/#/c/asklemmy
https://another.instance2/#/c/asklemmy
Then on your local #/c/asklemmy you would see the content of each of these?

**Comment by dessalines** [comment]
Yep.

**Comment by dessalines** [comment]
This will be part of  #145
