### ISSUE TITLE
Add emoji support

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#163]

**Comment by dessalines** [comment]
Prolly not gonna merge this cause it doubles the front end size.

**Comment by Restioson** [comment]
Woah, why?

**Comment by dessalines** [comment]
I'll add it, but try to use something smaller, and make sure mentions work.

**Comment by Restioson** [comment]
No, I mean what is it that makes it so big?

**Comment by dessalines** [comment]
Im not sure, just the large list of unicodes.

**Comment by Restioson** [comment]
Huh. Is it because of the font?
