### ISSUE TITLE
number of users inflated by 1

### ISSUE THREAD

**Issue by anewton1998** [dessalines/lemmy#165]
With a fresh installation I created only one user account. However, when I go to the front page, the users "badge" on the sidebar indicates there are two users.

**Comment by dessalines** [comment]
Ya this is verified, it creates an extra user [that I needed there for testing](https://github.com/dessalines/lemmy/blob/master/server/migrations/2019-02-26-002946_create_user/up.sql#L23), but is now unused. I just need to do a db migration to remove it.

**Comment by anewton1998** [comment]
Interesting... and the user name I picked was 'admin'.

Out of curiosity, what's the difference between `name`, `fedi_name` and `preferred_user_name`? I know pun is an activitypub thing.

**Comment by dessalines** [comment]
These are really just placeholders, I might need to add some more user tables or views as I get further in activitypub development. `fedi_name` would be the instance, and `preferred_user_name` is from activitypub, but I haven't done anything with that on lemmy.
