### ISSUE TITLE
community exists after being deleted

### ISSUE THREAD

**Issue by anewton1998** [dessalines/lemmy#167]
With a fresh install, I deleted the main community. However, it still shows up on my "subscribed" communities and I can click on it and go to that community.

It does say that community has been removed and the posts don't show, but the "create post" button is available and takes me to a create post page where the community is blank.

**Comment by dessalines** [comment]
Hrm... I kinda do want the community page to stay up so you can transfer ownership when I get to work on that, but you're right that at least the create post button should be disabled.
