### ISSUE TITLE
Numerous API issues

### ISSUE THREAD

**Issue by mister-monster** [dessalines/lemmy#171]
API issues:
GetSite takes no args but returns an error for missing field
GetUserDetails giving error for missing optional args
Search returns matching variant not found for same field values sent with web UI
GetPosts returns matching variant not found with valid args

Results gathered with new API test tool.

**Comment by dessalines** [comment]
I'm going through some of these now.

>  GetSite takes no args but returns an error for missing field

I found an error with this one, I'll have it fixed soon.

Which are the optional args on `GetUserDetails` that are messing up? For the user one of the user identifiers are required.

>  Search returns matching variant not found for same field values sent with web UI

I just tested this with websocat, its returning results okay... whats variant not found mean? Maybe you could put your post request here.

**Comment by mister-monster** [comment]
For "GetUserDetails" the following JSON string is sent:
{"op": "GetUserDetails", "data": {"sort": "Hot", "saved_only": True, "username": "dessalines"}}
The following value is returned:
expected value at line 1 column 64

For "Search" I have been unable to reproduce the problem after a few tries, I have not changed the input at all. Looks to either be resolved or be something intermittent. If it comes up again i will put a new issue in for it.

for "GetPosts" the following JSON string is sent:
{"op": "GetPosts", "data": {"type_": "All", "sort": "All"}}
the following is returned:
Matching variant not found.
It is possible i am sending an invalid type or sort, however looking at the API docs I don't think that is the case.

One additional note, {"op": "GetPost", "data": {"id": 1}} returns {"op":"GetPost", "error":"Couldn't find Post"} it is very useful for the API to reply with an error code in JSON.

**Comment by mister-monster** [comment]
For "Register" the following JSON string is sent:
{"op": "Register", "data": { "username": "test_user", "password": "Weh@veyouremails", "password_verify": "Weh@veyouremails", "admin": False}}
The following value is returned:
expected value at line 1 column 135
Based on the API documentation all required values have been sent.

I will be using this issue as a general API issue unless @dessalines you'd like me to open a new issue for every new API issue that comes up.

**Comment by dessalines** [comment]
>  {"op": "GetUserDetails", "data": {"sort": "Hot", "saved_only": True, "username": "dessalines"}}

I found that `true` works, no caps. true and false are lowercase in json. The same goes for the register error.

> {"op": "GetPosts", "data": {"type_": "All", "sort": "All"}}

There is no `All` sort type, you might mean `TopAll`: https://github.com/dessalines/lemmy/blob/master/docs/api.md#sort-types

I agree Its pry a good idea to use both error and return codes instead of strings, especially for internationalization purposes. I'll make a ticket for that.

**Comment by mister-monster** [comment]
Alright... Looks like the issue was passing "True" instead of "true" for bool values for all the issues except "GetSite".

I guess once the "GetSite" issue is fixed this issue can be closed, it has been solved.
