### ISSUE TITLE
Add a license to user generated content (?)

### ISSUE THREAD

**Issue by ghost** [dessalines/lemmy#172]
Should user generated content be published under a certain license? 

Recently I've found out that Coreboot (a popular FOSS project) is retiring their wiki because:

> content isn't properly licensed (since we never asked authors what license they want or told them what license any contributed text would be under). This also means that we can't migrate them to the new system.

https://www.reddit.com/r/coreboot/comments/bsktmt/need_info_for_elitebook_8470p/eonyt5e?utm_source=share&utm_medium=web2x

If you do decide that we need to add one, when should we notify the user about it? When he writes something (a comment or a post) for the first time or ...?

But also, what license should we pick? https://www.gnu.org/licenses/licenses.html
Or we could let the user pick a license from a list of predefined ones?

**Comment by dessalines** [comment]
The other fediverse projects use the AGPL, and so does this. I have no problem with commenters claiming it, but I don't want to make them accept a license right now.

**Comment by Zig-03** [comment]
I'm not sure the GPLs can be used for "text", usually they are some kind of CC, like CC BY-SA 4.0 or CC BY-ND 4.0 etc.
