### ISSUE TITLE
Use error and return codes rather than strings, for internationalization.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#174]
#171

**Comment by Restioson** [comment]
One could return an enum with data, perhaps? Then deser and match on it in client.

**Comment by dessalines** [comment]
Hehe funny you should say, I actually use enums on both the front and back end, but convert them to strings back and forth. Mainly because in APIs ppl like to see the command as a string rather than as a number. 

But yeah this will be going back to that for the error and return codes at least.

**Comment by dessalines** [comment]
Dup of #53
