### ISSUE TITLE
Discussion | Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [dessalines/lemmy#176]
**Objective**: Enable/Create a Lemmy instance(s) hosted over I2p.
The end-goal is that the end-user will only need to connect to Lemmy using I2p.

**Description**: Explore possibility of Lemmy instances utilizing the .i2p TLD and any issues that may arise.

**Why?**: Many reasons, mainly to create better privacy and security but also to support decentralized web communications.

**The issue**: Most ActivityPub sites are on the clearnet, how would an i2p instance communicate? Should a proxy (example: false.i2p) be used?
Or would the instance communicate with other instances over clearnet?

**Related Links**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/

https://www.wikipedia.org/wiki/I2p

___________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/75725023-discussion-support-i2p)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=75725023)](https://www.bountysource.com/issues/75725023-discussion-support-i2p)

**Comment by dessalines** [comment]
@ghbjklhv I've never heard of this before. So what does it take for a webserver to run on it? Can anyone just run any web services on it?

**Comment by mister-monster** [comment]
Dessalines from what I understand i2p is a routing protocol for obfuscation somewhat similar to Tor.

I haven't really thought about it but I do believe that social software should be able to run on networks like this, I wonder if a server running over i2p would even be able to federate with clearnet servers or if it would be a separate federation. I'm pretty sure Mastodon supports Tor, not sure about i2p but I assume some insight could be had by looking in to how Mastodon works in those circumstances.

**Comment by Verifirs** [comment]
You can configure an I2P client (I2PD for example) to use an outproxy for talking to clearnet. By default it tries to use Tor.

**Comment by LoveIsGrief** [comment]
I2P is basically TOR that isn't built with outproxies in mind. It's an anonymous overlay network optimized for P2P services. Nodes on the network can create hidden services. Allowing lemmy to use I2P would provide 2 possibilities:

 - being accessible from the a clearnet IP and I2P
 - or only only on I2P

The latter would provide all the advantages of a hidden service. Tight integration would be beneficial, but I2P already does provide a way of acting as a proxy `i2p darknet --> i2p service --> lemmy` (known as a tunnel in I2P)

http://localhost:7657/i2ptunnel/edit?type=httpserver
![screenshot](https://user-images.githubusercontent.com/2829538/89560990-29c7dc00-d818-11ea-9247-977642c5a36a.png)

Lemmy might just have to provide a mode where it doesn't communicate through any port but the one it uses in order not to leak data, but putting it in a VM or container that has no external network access. Does Lemmy require any other ports besides 80 or 443?

**Comment by dessalines** [comment]
I have no idea what any of this means. You can run lemmy at any port you want, check the docker install instructions.
