### ISSUE TITLE
Is it possible use sqlite instead of postgres?

### ISSUE THREAD

**Issue by hardliner66** [dessalines/lemmy#181]
Is there any way to use sqlite instead of postgres for a local test installation? I don't want to install a db just for testing a software.

**Comment by asonix** [comment]
It is not, currently. This library uses Diesel's `postgres` feature, and in turn relies on postgres's specific quirks (`like` being case-sensitive, for example). Additionally, the migrations for this project are written in postgres-flavored sql. Maintaining compatibility with multiple databases with diesel isn't feasible right now.

**Comment by dessalines** [comment]
Thx @asonix . I could see adding support for sqlite if this were a local only application, but its supposed to run on a server, and will need the read+write capabilities that sqlite wasn't made for.

@hardliner66 I suggest just following the [docker install](https://github.com/dessalines/lemmy#docker), it'll set up the postgres db for you.

**Comment by decentral1se** [comment]
Sorry for necroposting this but I was hoping it could be re-opened? `sqlite` support would align with the https://join-lemmy.org/docs/users/06-other-features.html#easy-to-install-low-hardware-requirements feature and support low resource environments. It's also more convenient for small scale installs. I don't understand the objection in https://github.com/LemmyNet/lemmy/issues/181#issuecomment-512934261?
