### ISSUE TITLE
Use postgres-alpine and persist in a volume from the codimd example

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#197]

**Comment by dessalines** [comment]
Instructions if any errors:

```
./docker_db_backup.sh # back up the db

# Clear all dbs and volumes
docker stop lemmy_db_1
docker rm lemmy_db_1
docker volume rm lemmy_db

# Remake the postgres volume
docker-compose up -d # unfortunately this builds the schema from scratch, which we have to drop
docker exec -i lemmy_db_1 psql -U rrr DROP SCHEMA public CASCADE;
docker exec -i lemmy_db_1 psql -U rrr create SCHEMA public;
cat db_dump  |  docker exec -i lemmy_db_1 psql -U rrr # restores the db

**Comment by Nutomic** [comment]
I'm just looking at your docker-compose.yml, is there any reason that you have 2 copies of that file? (one in the root folder and one in the docker subfolder)

Also, is there any particular reason why you are not running nginx as a Docker container as well?

For reference, [this docker-compose file](https://gitlab.com/Nutomic/peertube-compose/blob/master/templates/docker-compose.yml) is what I am using for my Peertube instance

**Comment by dessalines** [comment]
> Edit: Looks like one docker-compose is for development, and one for production?

Yup that's right. I can't put the dev one in anything but top level unfortunately because docker doesn't let you add things outside the project context, IE `COPY ../`, apparently for security reasons.

**Comment by dessalines** [comment]
I didn't want to add an extra nginx layer unecessarily bc ppl might already be running multiple services on one machine, and would want to define their own nginx or apache configs.

**Comment by Nutomic** [comment]
> Yup that's right. I can't put the dev one in anything but top level unfortunately because docker doesn't let you add things outside the project context, IE COPY ../, apparently for security reasons.

I dont think that matters for the docker-compose file. For the Dockerfile, you can put it in a subfolder and use a command like `docker build . -f ./support/docker/production/Dockerfile.stretch` (from [here](https://github.com/Chocobozzz/PeerTube/blob/develop/support/doc/docker.md#build-your-own-docker-image)).

>I didn't want to add an extra nginx layer unecessarily bc ppl might already be running multiple services on one machine, and would want to define their own nginx or apache configs.

In that case, we can just have Ansible configure the local nginx installation and make Lemmy available through that.

**Comment by dessalines** [comment]
I'll try this out

**Comment by dessalines** [comment]
Dang, okay that was a lot easier than I thought lol, thanks! I just had to add this to the docker-compose:

```
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
```
