### ISSUE TITLE
Dont use :latest Docker tag

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#199]
https://github.com/dessalines/lemmy/blob/master/docker/docker-compose.yml#L17

This is generally considered bad practice, especially for production. Here are some links about it:

https://vsupalov.com/docker-latest-tag/
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375

**Comment by dessalines** [comment]
Ya ur def right, I've gotten burned by that more than once.
