### ISSUE TITLE
Improve site security

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#208]
https://observatory.mozilla.org/analyze/dev.lemmy.ml

Content Security Policy is tricky and needs a lot of testing, so we can probably leave that for later. The others are just simple headers that need to be set:

- [ ] HTTP Strict Transport Security (this should be set in nginx so the admin can easily change it)
- [ ] Referrer Policy
- [ ] X-Content-Type-Options
- [ ] X-Frame-Options
- [ ] X-XSS-Protection

**Comment by dessalines** [comment]
I'd like to add this to the [nginx config section of the readme.](https://github.com/dessalines/lemmy#nginx-config) Seems like a good idea to abstract it rather than hardcoding it into the rust server.

**Comment by Nutomic** [comment]
That makes it more difficult to change later. Eg in case you want to allow people to embed Lemmy posts on other sites (X-Frame-Options). But I guess for most of them it doesnt matter. 

I added a full nginx config in #205, so I can add the headers in there.

**Comment by dessalines** [comment]
Thx a ton for this, I added these to the dev server and the communism one, and its getting a B rating now:
https://observatory.mozilla.org/analyze/dev.lemmy.ml

**Comment by Nutomic** [comment]
No problem! Like I said, CSP is the main thing thats missing, but as I said that needs a lot more testing compared to the other headers.
