### ISSUE TITLE
ActivityPub Test Suite

### ISSUE THREAD

**Issue by physkets** [dessalines/lemmy#212]
It would be nice if you could add the test suite and submit the report so that the compatibility with the protocol is clear:  
https://activitypub.rocks/implementation-report/

**Comment by AutomCoding** [comment]
The test server has been down for more than a year: [Gitlab issue](https://gitlab.com/dustyweb/activitypub.rocks/issues/9)

**Comment by dessalines** [comment]
In that case I'm gonna close it.
