### ISSUE TITLE
Upvoting on mobile sometimes highlights vote number

### ISSUE THREAD

**Issue by PopeRigby** [dessalines/lemmy#216]
[Here's](https://pixelfed.social/p/PopeRigby/68869490158473216) a video of it happening

**Comment by dessalines** [comment]
I have this same bug, but only on FF and its variants for android. It also makes it really hard to test too, cause every thing I change has to be deployed to the dev server. But ya this is a legit bug.

**Comment by dessalines** [comment]
Fixed by https://github.com/dessalines/lemmy/commit/d1c3e29dc93820e8a40a6c6ebe551de9d9d109a3
