### ISSUE TITLE
Mobile UI suggestions

### ISSUE THREAD

**Issue by PopeRigby** [dessalines/lemmy#222]
- Add [alternating colors](https://imgur.com/a/KVhIgos) to divide posts. An alternative to to this would be having [dividing lines](https://imgur.com/a/dytL8Nn) between them. 
- Have [right-aligned buttons](https://imgur.com/a/n0fqBWD) for commenting.
- Add [more padding](https://imgur.com/a/oSEtSKW) around vote buttons. Making them a little bigger also wouldn't hurt. 

This will make it look more like lobste.rs, which you said you took inspiration from.

**Comment by PopeRigby** [comment]
Has the dev instance been updated yet?

**Comment by dessalines** [comment]
Ya it has now.

**Comment by PopeRigby** [comment]
I think you may have made the dividers too dark. They're barely visible
![Screenshot_2019-08-29 Lemmy DEV](https://user-images.githubusercontent.com/20866468/63968039-8d1b8c80-ca53-11e9-92d8-87bbcec2cb06.png)

**Comment by dessalines** [comment]
I'll try to lighten it up a bit.

**Comment by PopeRigby** [comment]
Hmm. That looks quite good on mobile but seems a little strange on desktop. Have you tried putting a border around [this](https://user-images.githubusercontent.com/20866468/63980384-4720f180-ca70-11e9-9bcf-e3d056529f32.png) part?

**Comment by dessalines** [comment]
I have, it doesn't look good bordered.

**Comment by PopeRigby** [comment]
Huh. Have you tried alternating colors like [this](https://user-images.githubusercontent.com/20866468/63982519-a8988e80-ca77-11e9-821a-f49bc37ecf96.png)?

**Comment by dessalines** [comment]
No I haven't, I'm not a fan of that.

**Comment by PopeRigby** [comment]
This might be annoying, but maybe just get rid of the dividing lines?
