### ISSUE TITLE
Request: Support Monero (XMR) donations

### ISSUE THREAD

**Issue by Andrewskiz** [dessalines/lemmy#224]
Hey, it would be great if you had a Monero wallet address we could send donations to.

**Comment by dessalines** [comment]
Sure thing.
 `41taVyY6e1xApqKyMVDRVxJ76sPkfZhALLTjRvVKpaAh2pBd4wv9RgYj1tSPrx8wc6iE1uWUfjtQdTmTy2FGMeChGVKPQuV`
