### ISSUE TITLE
Flairs, Themes, Community Customization

### ISSUE THREAD

**Issue by farmerrae** [dessalines/lemmy#228]
It would be nice to be able to customize communities to be more pleasing and unique to interact with. As well, pinning posts, crossposting, and onsite image hosting would be good additions.

**Comment by dessalines** [comment]
Flair issue #184 

Cross posting #131 , working on this, should be mostly done soon.

Image hosting I'm not gonna do right now for reasons in here: #210 

As for pinning posts, it should maybe have its own issue, I'm undecided about adding pins, stickies, etc, bc it adds clutter and you can easily pin things to the sidebar already, which is visible from every page in your community.
