### ISSUE TITLE
change repo tag from `typescript` to `typescript` and `rust`

### ISSUE THREAD

**Issue by icyhat** [dessalines/lemmy#230]
Hi there guys,

I searched a lot of times about rust forum framework, but due to its tag is typescript,which is hard to find.

Shall we add `rust` tag on this repo?

**Comment by dessalines** [comment]
How do I do that.

**Comment by icyhat** [comment]
well, i searched and found nothing to show 2 programming languages.

But if you want replace `typescript` to `rust`
1. create a file under root path: `.gitattributes`
2. write content below to this file
```
* linguist-vendored
*.rs linguist-vendored=false
```

As for topics, you can add as many as you want, just click the repo and click `Manage topics`.

**Comment by dessalines** [comment]
Hey thanks, I didn't expect that to work for github but it did! Should be good now.
