### ISSUE TITLE
[Feature] Support BSD

### ISSUE THREAD

**Issue by ggg27** [dessalines/lemmy#233]
**Feature**: Add installation instructions for BSD users.
(i.e DragonFly BSD, NetBSD, e.c.t)

**Related Resources**:
- https://wiki.freebsd.org/Rust
- https://www.dragonflybsd.org/Rust_Support/
- https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/lang/rust/README.html
- https://www.reddit.com/r/rust/comments/7hgstc/theo_de_raadt_on_integrating_safe_languages_like/
_______________
**Note For OpenBSD Users**:
I am personally a big fan of OpenBSD but they are still W.I.P for Rust:
https://github.com/dhuseby/rust-cross-openbsd#rust-cross-openbsd

**Note**: Docker is not supported on OpenBSD (as well as some less popular BSDs), as they are Linux-specific. Some workarounds are available: http://openbsd-archive.7691.n7.nabble.com/Docker-on-OpenBSD-td275749.html

______________

**NetBSD Note**: 
NetBSD supports Ansible: [https://pkgs.org/download/ansible](https://archive.is/Eh1Kn)

**Comment by dessalines** [comment]
I'm not sure what you need from me for this. If docker doesn't work, and the [local installation instructions](https://github.com/dessalines/lemmy#local-development) don't work because you can't run rust, postgres, and yarn, there's not much I can do.

**Comment by ggg27** [comment]
> you can't run rust, postgres, and yarn, there's not much I can do.

@dessalines OpenBSD doesn't support Rust but other OSes do (to varying degrees).


> local installation instructions

Sorry, I thought this was only for testing. When I have time I'll try to install this in a VM.

**Comment by dessalines** [comment]
Cool.
