### ISSUE TITLE
Add option for instance owners to disable downvotes

### ISSUE THREAD

**Issue by PopeRigby** [dessalines/lemmy#239]
Some instance owners might not like the idea of downvotes, so an option to disable them (or voting in general) would be good.

**Comment by growl360** [comment]
Really good idea. It could also solve the problem of circlejerks.

**Comment by StaticallyTypedRice** [comment]
> Really good idea. It could also solve the problem of circlejerks.

On the other hand, it could turn a community into shitpost central like Facebook and YouTube comments.
