### ISSUE TITLE
Blank page when accessing a post page on Chrome

### ISSUE THREAD

**Issue by mlaunois** [dessalines/lemmy#247]
Randomly, if a post page is loaded in a new tab on Google Chrome, a blank page might appear instead of the Lemmy user interface, with the following error:

```
Refused to execute script from 'https://dev.lemmy.ml/static/c27b6f49-app.js'
because its MIME type ('text/html') is not executable, and strict MIME type
checking is enabled.
```

Even trying to load directly `c27b6f49-app.js` does not work, and yields this HTML instead of JavaScript:
``` html
<html lang="en">

<head>
        <!-- Required meta tags -->
  <meta name="Description" content="Lemmy">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/svg+xml" href="/static/assets/favicon.svg" />                                                                                                     
        <link rel="apple-touch-icon" href="/static/assets/apple-touch-icon.png" />                                                                                                              
  <script async src="/static/assets/libs/sortable/sortable.min.js"></script>                                                                                                                    
</head>

<body>
        <div id="app"></div>
        <script   type="text/javascript" src="/static/c27b6f49-app.js"></script>
</body>

</html>
```

**Comment by dessalines** [comment]
This pry isn't a bug, if you do a page refresh on anything that isn't the home page, the browser router won't work. There's an nginx config on the main page if you need the routing to work correctly on page refreshes or new page loads.

**Comment by mlaunois** [comment]
This also happens on the home page:
![Home page screenshot](https://user-images.githubusercontent.com/47182594/63958819-33cf4f80-ca8b-11e9-9bfa-c943711dacb3.png)

**Comment by Nutomic** [comment]
I'm getting the same problem on dev.lemmy.ml now, cant open it at all. communism.lemmy.ml is working fine. Using latest Firefox.

**Comment by mlaunois** [comment]
@dessalines @Nutomic If this can help to solve this problem, here are the response headers I get for `c27b6f49-app.js`:

```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 29 Aug 2019 17:21:11 GMT
Content-Type: text/html
Content-Length: 593
Connection: keep-alive
Vary: Accept-Encoding
last-modified: Thu, 29 Aug 2019 04:31:13 GMT
accept-ranges: bytes
etag: "27:251:5d675511:0"
content-disposition: inline; filename="index.html"
Expires: Sat, 28 Sep 2019 17:21:11 GMT
Cache-Control: max-age=2592000
Strict-Transport-Security: max-age=63072000
Referrer-Policy: same-origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-XSS-Protection: 1; mode=block
```

**Note: this is the `X-Content-Type-Options: nosniff` that instructs browsers to check strictly the MIME type of the script, and to not execute it if it is not `text/javascript`. There is an associated Chromium bug [here](https://bugs.chromium.org/p/chromium/issues/detail?id=180007).**

**Comment by Nutomic** [comment]
Ah then it looks like correct behaviour, and Lenny just needs to set the correct content-type.

**Comment by dessalines** [comment]
You might be right, I'm looking at this now.

**Comment by dessalines** [comment]
Okay this is fixed now, I realized what it was, and I'm not smart. 

The nginx url rewrite necessary for the browser router, has `/c+` in the regex, so that it routes correctly to communities, but unfortunately it has the side affect of any resource that started with that, IE, `c-whatever.js` to be served at the wrong url. I'll change the default nginx config, as well as on the servers I'm running lemmy on.

My bad.

**Comment by dessalines** [comment]
Let me know if you still get the same issue.

**Comment by mlaunois** [comment]
I no longer get this issue, thanks!
