### ISSUE TITLE
Add 'Edit' and 'Preview' tabs to body text area 

### ISSUE THREAD

**Issue by PopeRigby** [dessalines/lemmy#253]
Something like [this](https://user-images.githubusercontent.com/20866468/64053449-41daaa00-cb37-11e9-8277-5808ed3a1786.png). Then you can switch between the two tabs to see how your markdown will render.

**Comment by dessalines** [comment]
I like this idea. 

Possibly something like:

![](https://i.imgur.com/DxeCTCL.png)

But I also want to add 

- Image Upload
- Formatting Help

**Comment by PopeRigby** [comment]
I think for UX, it would be best to do the two tabs at the top, like GitHub
![Screenshot_20190831-180925](https://user-images.githubusercontent.com/20866468/64070662-9c990200-cc1a-11e9-9ae2-e212e6df20da.png)

**Comment by dessalines** [comment]
This is on dev now, in a way that I could stand, for both posts and comments.
