### ISSUE TITLE
Automatically hyperlink when mentioning a user or community

### ISSUE THREAD

**Issue by PopeRigby** [dessalines/lemmy#256]
Like how Reddit does it, when you just type 'r/something' or 'u/somethingelse', it automatically turns that text into a hyperlink to the user or subreddit.

**Comment by dessalines** [comment]
I just did this today, the trigger character is `@`

**Comment by PopeRigby** [comment]
I wasn't clear enough with my original description. I updated it. It's a different thing from #129.

**Comment by PopeRigby** [comment]
I wasn't clear enough with my original description. I updated it. It's a different thing from #129. Currently you have it setup as some markdown to reflect the link, like this `[\u\test](\u\test)`, whereas Reddit will automatically interpret r/test as a subreddit, without you having to fiddle with markdown.

**Comment by dessalines** [comment]
I thought about it, but didn't want to do that, both because users might live on other domains, and because that requires parsing the comment for specific strings, which I'd rather not do. I'd rather have all links be explicit, and just use autocomplete as a helper there.

**Comment by PopeRigby** [comment]
> both because users might live on other domains

Couldn't you do something like `@poperigby@dev.lemmy.ml`?

> because that requires parsing the comment for specific strings

Oh. Is that resource intensive?
