### ISSUE TITLE
Content doesnt appear on search engine

### ISSUE THREAD

**Issue by freshy969** [dessalines/lemmy#261]
Hello 👋
I want to say thanks for taking out your time to add new feature on the script.

I found out that lemmy doesn't content doesn't appear on search engines? 

I try a lot of post made on the site but it doesn't appear on search engine... 

Hmm!! When will lemmy be able to appear on search engine?? Will it come on verse 1?

Also will they be any possible that admin can or will have the power to create forum or category alone...

**Comment by dessalines** [comment]
Dup of #173 .

> Also will they be any possible that admin can or will have the power to create forum or category alone...

I'm not sure what you mean by this, admins can already create communities. The categories are tougher because right now they're all hardcoded in english, which I want to get away from, but have to think of a good way to do this.

**Comment by freshy969** [comment]
So does the content been indexed by any search engine ?

**Comment by dessalines** [comment]
Yes, the pages can be indexed now that the UI is isomorphic.

**Comment by freshy969** [comment]
Thanks @dessalines for your reply....but why is that URLs are not SEO friendly?? Eg, yoursite.com/frest-seo-tool-optimize-your-site insteady the current one showing..

Don't you think it better to give best SEO practices???

**Comment by dessalines** [comment]
Could you be more specific?

**Comment by freshy969** [comment]
@dessalines this the traditional URL of a give post comes with on your script...https://lemmy.ml/post/71502 right.. I was thinking that it should be some like https://lemmy.ml/post/frest-seo-tool-optimize-your-site

**Comment by dessalines** [comment]
> However, there should be room for someone to place Adsense or any form of advertising on his own since it open source project .

We will never allow ads, or support ppl who want to add ads, ever.

And your idea of englishifying the post url based on its title doesn't add anything for us, and doesn't help SEO in any way either.
