### ISSUE TITLE
[Discussion] Renaming Lemmy

### ISSUE THREAD

**Issue by ghbjklhv1** [dessalines/lemmy#263]
**Discussion**: Perhaps it is time to rename Lemmy?
**Why?**: For starters, the current domain owner wants several tens of thousands of dollars for the domain "lemmy.com". _Despite, it being available for purchase a few months ago_.

It seems to  have been caught by some tricky domain snipers and not going to the community.

______________________

**Issue**: My fear is that the owners of Lemmy.com will monopolize the market and down-play many of the essential reasons a user would like to use ActivityPub.

**Comment by dessalines** [comment]
I really like the name, don't wanna change it.

I also don't really care about domain names, esp since lemmy.com representing this shouldn't really be used by anyone... lemmy is just the software powering the instances. People can always use subdomains too like `lemmy.mysite.com`.
