### ISSUE TITLE
Rate limits apply when API requests fail

### ISSUE THREAD

**Issue by mlaunois** [dessalines/lemmy#273]
Rate limits on API requests apply, even if the request fails because of an error in user input. They should be ignored when there is an error with the sent JSON data (or at least made more flexible).

**Example:**  
If someone attempts to register, but failed, for example because he mistyped his password:

![Passwords do not match.](https://user-images.githubusercontent.com/47182594/64627771-c357f500-d3df-11e9-8229-e426754a2c39.png)

He cannot try again to register:
![Too many requests. 1 per 3600 seconds](https://user-images.githubusercontent.com/47182594/64628032-3a8d8900-d3e0-11e9-8907-3b32d8551b34.png)

(This is the specific case of account registration, but this applies as well for any rate-limited action.)

**Comment by dessalines** [comment]
Hrm, yup this does look like a bug. IMO it should really only rate limit on registering, logins shouldn't have one.
