### ISSUE TITLE
Suggestion: things that move should not autoplay

### ISSUE THREAD

**Issue by zacanger** [dessalines/lemmy#288]
Videos and GIFs, or at least videos. This was a really nice feature that a lot of folks appreciated when Mastodon added it (and the Masto FE is React, so might be able to port over that code).

**Comment by dessalines** [comment]
Okay I've got this now for videos, but unfortunately it doesn't look like there's a way to stop gifs from autoplaying. The best I have rn is that pictshare (the self-hosted mage uploading service this comes with), will auto-convert uploaded gifs to mp4s.
