### ISSUE TITLE
mySQL / MariaDB support?

### ISSUE THREAD

**Issue by poVoq** [dessalines/lemmy#289]
Any chance for this to get mySQL / mariaDB support?

I know, for most setups it doesn't really matter, but in some special cases (such as a managed mySQL database service) it would be cool to have the choice, especially given the likely high database size once the Fediverse support is added.

Thanks for considering.

**Comment by dessalines** [comment]
Unfortunately no, this would be too much work to do. Some of the datatypes wouldn't be supported, and the ORM (diesel) is postgres specific.
