### ISSUE TITLE
Lemmy-hosted videos don't expand or open on click

### ISSUE THREAD

**Issue by zacanger** [dessalines/lemmy#291]
Example: https://communism.lemmy.ml/post/1083

**Comment by dessalines** [comment]
Ya this is definitely a bug.

**Comment by dessalines** [comment]
Okay I've got this now for videos, but unfortunately it doesn't look like there's a way to stop gifs from autoplaying. The best I have rn is that pictshare (the self-hosted mage uploading service this comes with), will auto-convert uploaded gifs to mp4s.
