### ISSUE TITLE
re-creating the server didn't log out the web clients.

### ISSUE THREAD

**Issue by docquantum** [dessalines/lemmy#292]
So, I recreated the stack (docker-compose) and re-setup the server.

New posts, in a community, seem to be made on a different user's behalf.

Not sure how/why this happens, but this is a concerning issue.

**Comment by docquantum** [comment]
Might be that another user was still logged in with some auth token, and it defaulted to whatever user existed

**Comment by docquantum** [comment]
Could be that the other poster's user ID is the same as the new one that is mine. I'd assume that DB/stack recreation would require new auth keys however, so odd that it didn't kick him out on the cached web-ui

**Comment by dessalines** [comment]
Did you log out and log back in. Also remember the database is persisted in a volume. So you need to remove the database volume when you re-set up the server.

**Comment by docquantum** [comment]
Yes, I actually mapped the DB and pictshare to specific locations, cleared both out, recreated the server. The other user wasn't logged out, was still able to post. My assumption is that his user id with the old DB was the one I registered a new user with, leading to this situation.

**Comment by dessalines** [comment]
I'm not sure if I'd consider this a bug. The JWT secret on the server likely didn't change when you created a new instance, so your token still counted as verified on the server (IE the server created that token), and it took that equivalent user ID. An easy way to de-authorize everyone when you spin up a new server, would be to change that JWT secret in the docker config. Does that make sense?

**Comment by docquantum** [comment]
Yes, makes sense. Feel free to close it if you don't plan on working on some sort of system that would bump people out on server recreation.

**Comment by dessalines** [comment]
Ya, its def good to have this issue just to show ppl what the fix is, if they do this in the future.

For the record: if for any reason you need to log out all clients, just change the `JWT_SECRET` in the docker file.
