### ISSUE TITLE
Image Posting

### ISSUE THREAD

**Issue by mflsim** [dessalines/lemmy#320]
The ipv6 url doesnt work
Example: **![] (http://[ipv6 address]/pic.jpg)**

**Comment by dessalines** [comment]
Could you give a real example? I don't know if markdown supports ipv6 at all. Plus you have a space in there.

**Comment by mflsim** [comment]
If i post a picture like that ![](http://1.2.3.4/pic.jpg) or ![](http://domen.org/pic.jpg) fine works (JS upload picture)
With ipv6 doesnt work ![](http://[ipv6]/pic.jpg) (blank)

**Comment by mflsim** [comment]
new details:
chrome: i[] (http://[ipv6]**:**/pic.jpg) works! (**:** added)
firefox: doesnt help

ipv6 like 201:b614:c68e:b27f:dc0e:e8ec:15d0:2eb0

ps.
look like **![] (http://[201:b614:c68e:b27f:dc0e:e8ec:15d0:2eb0]/pic.jpg)**

**Comment by dessalines** [comment]
You'll have to give me a real world link, or I can't test this.

**Comment by mflsim** [comment]
> You'll have to give me a real world link, or I can't test this.

I keep the lemmу on the server in the overlay network Yggdrasil
You can check here: http://[201:b614:c68e:b27f:dc0e:e8ec:15d0:2eb0]/  (yggdrasil subnet)

**Comment by dessalines** [comment]
Hrm that link didn't work from my browser... I'm not sure how to test.
