### ISSUE TITLE
case sensitive usernames

### ISSUE THREAD

**Issue by aspera-non-spernit** [dessalines/lemmy#328]
It is possible to create an account with almost identical usernames:

Examples:

- adastra
- AdAstra
- Adastra

This should be avoided,

**Comment by dessalines** [comment]
Yes, I wasn't really sure the best way (I think most sites allow case sensitive usernames). 

I put some restrictions on symbols, but uppercase letters are fine. I'm not sure if I want to enforce case insensitive uniqueness on names, even if it might be annoying that `The_Human` , `THE_HUMAN` and `the_human` are different users.

If enough people want this I can consider re-opening.
