### ISSUE TITLE
Users cannot navigate to their own profile from someone else’s profile

### ISSUE THREAD

**Issue by StrangePeanut** [dessalines/lemmy#331]

**Comment by dessalines** [comment]
I can't recreate this. Browser, steps, console logs?

**Comment by StrangePeanut** [comment]
Reproducible on Chrome, Edge and Firefox

 1. Navigate to a user profile
 2. Attempt to navigate to your own user profile

[Video](https://i.imgur.com/8ocRz8F.mp4)

**Comment by dessalines** [comment]
oooh okay yeah you're right, I thought this was when you mention a user in a comment, and go from one overview to another, this is broken when you use the top right menu.
