### ISSUE TITLE
Problems with interface

### ISSUE THREAD

**Issue by anarcobuda** [dessalines/lemmy#332]
I use a machine running Parabola GNU/Linux-libre and free software GNU IceCat as my browser.
![Screenshot from 2019-11-11 13-50-56](https://user-images.githubusercontent.com/56075993/68605817-fcc2e480-04a4-11ea-9f65-18857679edb2.jpg)
This is the interface that I see, and it's largely un-readable.

I then tried the same link on Tor browser, and I got this result:
![Screenshot from 2019-11-11 14-04-01](https://user-images.githubusercontent.com/56075993/68606019-6cd16a80-04a5-11ea-890e-fdb94dce619d.jpg)
Substantially different, surely. Is there any way to have more control over the interface to prevent these differences based on browsers?

**Comment by anarcobuda** [comment]
I realized these are different themes for Lemmy, but what could be causing one being the default on different browsers?

**Comment by dessalines** [comment]
Someone else mentioned that the CSS loading / unloading is broken in ICEcat. I'm not sure there's anything I could do for this one, I've tested on FF, chrome, and several mobile browsers, and the CSS works correctly. Its an icecat bug.

Here's the code that sets the theme: https://github.com/dessalines/lemmy/blob/master/ui/src/utils.ts#L292
