### ISSUE TITLE
Frontend loads all themese from server

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#333]
It would be better if only the active theme was loaded.

![Screenshot_20191111_182929](https://user-images.githubusercontent.com/1044450/68607630-f7679900-04a8-11ea-87ff-b68006a55cd1.png)

**Comment by dessalines** [comment]
That's fair, I'm not 100% positive that there's a way to do theme switching without loading all the themes, but I can try. Relevant code here:

https://github.com/dessalines/lemmy/blob/master/ui/src/utils.ts#L292

**Comment by dessalines** [comment]
Okay I figured out a fix for this, so now only the darkly theme is loaded in `index.html` . The caveat is that if you use a different theme, you will see a slight flicker as the site loads, since it has to load that theme dynamically, but it'll be before any data anyway.
