### ISSUE TITLE
Usernames are not case sensitive

### ISSUE THREAD

**Issue by growl360** [dessalines/lemmy#341]
So some guy on the Lemmy Dev instance made 4 accounts u/adstra, Adstra, ADstra and some more. It's a pretty big issue having case sensitive names.

**Comment by dessalines** [comment]
I commented on this over there, I'm not sure that its good behavior to enforce case sensitivity at all. It might be annoying that `the_human` `The_Human` and `THE_HUMAN` are different users, but there's not necessarily anything wrong with it. I'll have to wait for a lot of ppl to chime in on this one.

**Comment by dessalines** [comment]
I'm thinking this is better to have sooner than later. Here's the postgres command that can enforce case insensitive indexes: `CREATE UNIQUE INDEX email_unique_idx on users (LOWER(email));`

So far things I can think of that need this: 

user_.name, user_.email, user_.matrix_user_id, category.name, community.name
