### ISSUE TITLE
Lemmy can't be archived by any of the web archive services.

### ISSUE THREAD

**Issue by growl360** [dessalines/lemmy#347]
Dunno of this is intentional but archive.org and archive.is cannot archive any Lemmy pages or content.

**Comment by growl360** [comment]
Eg - http://web.archive.org/web/20191122064604/https://dev.lemmy.ml/

**Comment by dessalines** [comment]
This is because it's a dynamic web app whose content is loaded after the initial page load. If anyone knows a way to make react apps work with web archivers, let me know.

**Comment by dessalines** [comment]
Dup of #173

**Comment by growl360** [comment]
For the SEO have you tried logging into Google webmaster and fetching Lemmy? I've heard that Google supports JavaScript intensive websites.

I've found a few solutions for react apps.

1) redirect crawlers and bots to a different web page (a static version) (pretty sure Google will penalize you for this)

2) [no script html tag](https://www.advancedwebranking.com/blog/make-javascript-indexable-by-google/)

This article kind of explains the solution https://medium.com/on-archivy/javascript-and-archives-db32bc400263

**Comment by dessalines** [comment]
What's the solution there?

**Comment by growl360** [comment]
Sorry wrong link, it was supposed to be a Reddit link. 

The solution was to create an old.Dev.lemmy.ml (a static version of dev.lemmy.ml) and then people can archive pages from there and fetch to Google for SEO and to get it listed.

**Comment by dessalines** [comment]
I did try to do an isomorphic app ( and failed for various reasons, mainly that the data fetching doesn't work with websockets, and multi-lingual support doesn't work ). 

I might look at it again at some point, but its far down on my list.

**Comment by dessalines** [comment]
Closing this as dup of #226
