### ISSUE TITLE
Display subscribe buttons for RSS feeds, and add documentation to API.md

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#348]
Follow up for #344. The feed URLs look like this, with the sort parameter being optional:
```
/feeds/c/*community-name*.xml?sort=Top
/feeds/u/*user-name*.xml?sort=Top
/feeds/all.xml
```

**Comment by Nutomic** [comment]
We probably want to add some documentation for this as well? Especially the sort parameter, right now thats only in the code.

**Comment by dessalines** [comment]
Ya, oh crap I didn't add the sort stuff on the front end, oops.
