### ISSUE TITLE
Add private / user based rss feeds.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#349]
@Nutomic I'm also looking at reddit's user based / private rss feeds, [here](https://www.reddit.com/prefs/feeds/)

It doesn't use a post param like I thought, just a unique and private hash associated for that user, which it tells you never to share.  I'll probably use some kind of `hash(Settings::jwt_secret + the user's id)` to build a private rss id like reddit does. 

Then in keeping with your convention, the links would be:

```
/feeds/front/hashed_id*.xml?sort=X
/feeds/inbox/hashed_id.xml?sort=X&type=unread
```

Do you see any other links on that page that would be useful? They have ones for your own profile but that doesn't seem too useful. Inbox and Front page are the only ones I'd want.

#344 #118

**Comment by Nutomic** [comment]
The truth is, I'm not using rss feeds for reddit, and i'm not using planning to use them for lemmy. It just seemed like something that would be easy to implement. So I think we should just wait what people actually request for Lemmy.

**Comment by dessalines** [comment]
I got bored and added this anyway haha. It uses your jwt token on the front end to create the unique feeds for Inbox and Subscribed.
