### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#351]
Environment variables wont be enough at some point, unless we want to handle dozens of them. Maybe yaml, json or some other format? 

Of the existing env vars, at least the ones for rate limiting should be moved to a config file. Maybe also the domain var.

**Comment by dessalines** [comment]
I'd prefer JSON / JSON5 (the one that allows comments, and some parsers allow them anyways). Beyond that I don't have any preferences, as long as all the config is in a single file.

**Comment by dessalines** [comment]
[JSON5 rust library](https://docs.rs/json5/0.2.5/json5/index.html)

My question tho is, how that would work with docker. rn there's the `.env` file, passing things like the db location to `environment` in the `docker-compose`. I'll have to read about docker and passing config files.

**Comment by Nutomic** [comment]
Yeah it needs a volume, but I don't see anything wrong with that. And when it comes to things like nested data (eg the rate limiting vars), I think it would be much easier to use a json file instead of env vars that are completely independent.

We don't have to move everything to the config, things like the database address probably make more sense via env.

**Comment by Nutomic** [comment]
Also, not sure where you got the information about postgres or matrix, they both have config files.

[postgres](https://www.postgresql.org/docs/9.3/config-setting.html)
[matrix](https://github.com/matrix-org/synapse/blob/master/INSTALL.md) (search "configuration file")

**Comment by dessalines** [comment]
Sry, I was looking at the docker images, https://hub.docker.com/_/postgres

It does look like postgres has a way to also use a config file through a mounted volume like you say, the section there is called database configuration. 

It would make it easier, especially with having to add every new environment var to the .env and docker-compose files. If you'd like to do this I'd be happy to merge.

This is more of a thing to be aware of, is that anytime we add new things to the config, we have to make sure the rust reader is backwards compatible (I bet as long as the new fields are `Option<whatever>`, then the json parser will work fine if they're missing  / absent.

**Comment by Nutomic** [comment]
Okay Rust has some really good libraries. [This here](https://crates.io/crates/config) is the first one I found, and it has some cool features. Like reading from environment variables, live reload, multiple formats including [hjson](https://hjson.org/) (supports comments). Sounds good?

**Comment by dessalines** [comment]
Yup that looks good, use the hjson add-on there.

**Comment by dessalines** [comment]
homework lol. Nah just let me know if you'd like me to do this instead.

**Comment by Nutomic** [comment]
No its fine, I just didnt really have time yet to get started with it.

**Comment by dessalines** [comment]
No time constraints obvi, we out here doing free labor.
