### ISSUE TITLE
Allow disabling NSFW tags

### ISSUE THREAD

**Issue by khionu** [dessalines/lemmy#364]
I'm using Lemmy for a project-specific forum, and I would like to just not allow NSFW content, as it would be perceived as unprofessional.

I would imagine this working as content that is marked as NSFW wouldn't reach my instance of the federation, and my users couldn't create NSFW content.

**Comment by khionu** [comment]
Kudos to the quick resolution time! 💯

**Comment by dessalines** [comment]
No probs! I had some things in mind for 2 other similar issues, so it was easy to add this.
