### ISSUE TITLE
Outh2 support

### ISSUE THREAD

**Issue by fanux** [dessalines/lemmy#370]
How to using github to login lemmy? We need that badly

**Comment by Nutomic** [comment]
Why do we need that? Having a federated, open source project depend on something centralised and proprietary sounds wrong.

**Comment by fanux** [comment]
Because many coder to lazy to regist an account 🙂

**Comment by dessalines** [comment]
Agree with @Nutomic here. I don't know of any federated service, even matrix/riot, that has oauth.

**Comment by decentral1se** [comment]
> How to using github to login lemmy?
>
> I don't know of any federated service, even matrix/riot, that has oauth, especially for the purpose of proprietary-based logins.

https://matrix-org.github.io/synapse/latest/openid.html#github

I'm not arguing for Github logins but having OpenID Connect is super valuable for community-run digital communities.

**Comment by dessalines** [comment]
I don't know anything about OpenID, but if someone who knows about it wanted to create a connector, that'd be fine.
