### ISSUE TITLE
Use of outdated cryptography library in server

### ISSUE THREAD

**Issue by VanillaBrooks** [dessalines/lemmy#372]
`rust-crypto` is currently used in `password_reset_request_request.rs [here](https://github.com/dessalines/lemmy/blob/master/server/src/db/password_reset_request.rs#L49-L71):

```
use crypto::digest::Digest;
use crypto::sha2::Sha256;
// -- cut --
impl PasswordResetRequest {
  pub fn create_token(conn: &PgConnection, from_user_id: i32, token: &str) -> Result<Self, Error> {
    
    // here
    let mut hasher = Sha256::new();
    hasher.input_str(token);
    let token_hash = hasher.result_str();

    let form = PasswordResetRequestForm {
      user_id: from_user_id,
      token_encrypted: token_hash,
    };

    Self::create(&conn, &form)
  }
  pub fn read_from_token(conn: &PgConnection, token: &str) -> Result<Self, Error> {

    // here
    let mut hasher = Sha256::new();
    hasher.input_str(token);
    let token_hash = hasher.result_str();
    password_reset_request
      .filter(token_encrypted.eq(token_hash))
      .filter(published.gt(now - 1.days()))
      .first::<Self>(conn)
  }
}
```
These were the only entries I could find with basic grep-ing.

Based on the crates.io [entry](https://crates.io/crates/rust-crypto) `rust-crypto` has not been updated in four years. Would it be possible to swap this dependency to a more recently updated crypto library such as [sha2](https://crates.io/crates/sha2) ?

I am not an expert on the subject, but it appears more significant crates [trust `sha2`](https://crates.io/crates/sha2/reverse_dependencies) over [`rust-crypto`](https://crates.io/crates/rust-crypto/reverse_dependencies).

**Comment by dessalines** [comment]
Sure, I can try this out in a few days.
