### ISSUE TITLE
Use actix config to handle different paths

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#378]
https://actix.rs/actix-web/actix_web/struct.App.html#method.configure

Basically, we should add a seperate config to the actix app for each module. That means for example, all paths under `/feeds/` are handled by the feeds file/module, and all paths under `/c/` by the community file/module. That means we wont have conflicts in main.rs every time a route is changed.

**Comment by dessalines** [comment]
I agree. These could be placed in a folder called `routes`.

**Comment by Nutomic** [comment]
Well my proposal is to put the routes for each module seperately, so its not all in the same place. Putting it all into the same folder doesnt solve the problem at all.

**Comment by dessalines** [comment]
Yeah, the routes folder / module would have many separate files for the paths.

**Comment by Nutomic** [comment]
https://yerbamate.dev/dessalines/lemmy/pulls/8
