### ISSUE TITLE
Expose API over HTTP

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#380]
Right now the API is only available over websocket. It would be very useful if it was also available via HTTP as a REST API. Preferably without duplicating all the existing API code.

[See this document for an overview of the existing websocket API](https://github.com/dessalines/lemmy/blob/master/docs/api.md)

**Comment by dessalines** [comment]
For client-to-server apps, I would definitely prefer people use the websocket API, since its live-updating. The only two other platforms besides the web app that I can think of next for applications, are android and a terminal client, both of which would work fine with websockets.

**Comment by Nutomic** [comment]
There are also other use cases, for example gathering statistics that would most likely be happier with an HTTP API.

https://the-federation.info/lemmy

**Comment by dessalines** [comment]
That makes sense.

**Comment by Nutomic** [comment]
If you are interested in using the HTTP API, here is what it will most likely look like (you need to scroll up a bit). If you have any feedback, now is the best time for that.

https://yerbamate.dev/dessalines/lemmy/pulls/14/files#issuecomment-134
