### ISSUE TITLE
Upgrade to actix 2.0?

### ISSUE THREAD

**Issue by shirshak55** [dessalines/lemmy#392]
As actix is updated to 2.0 and is stable any plans for upgrading it in lemmy?

Thank You.

**Comment by dessalines** [comment]
I have other priorities at the moment, but if someone wants to do this I'd be more than happy to accept PRs.

**Comment by thebinarymutant** [comment]
I would love to help out over here but can someone guide me where do I start off from?

**Comment by shirshak55** [comment]
making function async using actix runtime etc. I think actix web has migration guide too.

**Comment by dessalines** [comment]
https://github.com/dessalines/lemmy/tree/master/server/src

The `routes`, `websocket` and `main.rs` files/folders have most of the actix stuff in them. It shouldn't be too difficult, except the websocket folder.

**Comment by Nutomic** [comment]
https://yerbamate.dev/dessalines/lemmy/pulls/11
