### ISSUE TITLE
Initial instance configuration based on config variables

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#404]
I am referring to the initial setup after installation, where you create the admin account and create the default community. It would be nice if this could be done via environment or config instead, so that a random person that accesses the website cant just finish the setup.

This would also be useful for testing, because we wouldnt have to manually configure our local test instances all the time.

**Comment by dessalines** [comment]
Agree this would make setting up federation tests a lot easier too.

**Comment by Nutomic** [comment]
Okay here is my proposal how to implement this:

We add a new config variable `admin_username`. This one is only used at the first start, and if it is present, an admin user is created with that username and a random password. The password is printed in the log (and can be extracted by Ansible). Once the admin logs in with that data, they can finish the setup by entering the site name and description.

**Comment by dessalines** [comment]
This is a good idea, but I think all of the setup vars should be in there, and also the password should be explicit in the `lemmy.hjson`, not generated, remember this isn't just for ansible, but for anyone doing this through docker or manually.


Here's all the site vars required for setup: 
```
pub struct CreateSite {
  name: String,
  description: Option<String>,
  enable_downvotes: bool,
  open_registration: bool,
  enable_nsfw: bool,
  auth: String,
}
```
So the `lemmy.hjson` will have an optional commented out section, with the admin_username, admin_password, and those above.

**Comment by Nutomic** [comment]
Okay that also works for me :D
