### ISSUE TITLE
Fix r2d2 pooling with actix 2.0

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#409]
Based on this: https://github.com/actix/examples/blob/master/r2d2/src/main.rs#L15

**Comment by Nutomic** [comment]
What exactly is the reason for putting the db pool into the application state? Is that better than our current approach?

Actually I dont really understand the whole async in Rust yet, do you know a good guide about that?

**Comment by dessalines** [comment]
I'm not 100% sure, but I think having the pool in the app state allows it to properly check for blocks. If its outside the web worker, it might not be properly doing checks on the db pool and just opening up a threads.

I can say from experience with another project I just did this to, it made it so that I didn't have a lot of stalled out DB connections in a ton of different web threads.

I'm gonna do some before and after perfomance while i work on this too.

**Comment by dessalines** [comment]
btw here's an async guide I'm gonna read through too: https://rust-lang.github.io/async-book/01_getting_started/01_chapter.html
