### ISSUE TITLE
Set up gitlab mirror

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#41]

**Comment by Nutomic** [comment]
Did you setup a mirror? I couldnt see a link in the readme.

This seems really important to me, because Github is blocking lots of countries, incuding Cuba, Iran, Venezuela. That said, gitlab.com wouldnt be any improvement, but maybe something like [framagit](https://framagit.org/).

**Comment by dessalines** [comment]
It's hosted in 3 places rn, here, https://gitlab.com/dessalines/lemmy, and a personal
