### ISSUE TITLE
Add a contributing page

### ISSUE THREAD

**Issue by BatmanAoD** [dessalines/lemmy#429]
Adding a page for new contributors, with contribution guidelines and instructions, would probably be helpful for onboarding new contributors. The standard name for such a file is `CONTRIBUTING.md`. As an example, here is [Starship's contributing page](https://github.com/starship/starship/blob/master/CONTRIBUTING.md).

**Comment by dessalines** [comment]
Good idea.

**Comment by richardj** [comment]
Yes please! :)
