### ISSUE TITLE
Use interpolation i18n.t function instead of <T>

### ISSUE THREAD

**Issue by richardj** [dessalines/lemmy#430]
Right now, I see a lot of `<T i18nKey="value">#</T>` in the code. This wraps the translation into a `div` element, which results in nested elements.

Using the interpolation function you can directly inject the translation into the element, for instance:

```
<h4>{ i18n.t('key') }</h4>
```

edit: i see this method being used in the form attributes, but as far as i can see this can be used for element contents as well.

**Comment by dessalines** [comment]
This is doable, and probably a lot cleaner. I just have to remember to convert these:

```
<T
i18nKey="number_of_users"
interpolation={{
count: this.state.site.site.number_of_users,
}}>#
</T>
```

to `i18n.t('number_of_users'), {count: });`

**Comment by richardj** [comment]
I can pick that up. I started with `setup.tsx` and i can work my way through the components step by step.

**Comment by dessalines** [comment]
Sweet, thx.
