### ISSUE TITLE
Community edition title cannot be generated

### ISSUE THREAD

**Issue by martijnvwezel** [dessalines/lemmy#435]
Trying to generate a new title for a subLemmy, but somehow it says that there are space only there are no spaces

**Comment by dessalines** [comment]
Could you screenshot the error? Also what browser.

**Comment by martijnvwezel** [comment]
The error is now gone, but there is stille a error on the webpage:
![image](https://user-images.githubusercontent.com/4363788/72665046-29dfc600-3a05-11ea-84f1-04ef913c315a.png)
Chrome: Versie 79.0.3945.117 (Officiële build) (64-bits)

Is it possible that you restarted or updated the version?

**Comment by martijnvwezel** [comment]
I have the error back again:
![image](https://user-images.githubusercontent.com/4363788/72665279-03bb2580-3a07-11ea-99ee-68073c37a996.png)

**Comment by dessalines** [comment]
Yep that's okay, that's a minor error having to do with not fetching the site name. 

> `lowercase`
