### ISSUE TITLE
Generate documentation for HTTP API

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#437]
Would be cool if this could somehow be generated automatically. Here is some discussion about it.

https://github.com/fafhrd91/actix-web/issues/310

**Comment by dessalines** [comment]
Might be doable: https://paperclip.waffles.space/actix-plugin.html

But if it's not plug and play, then we can just use the existing docs.

**Comment by dessalines** [comment]
I added the new HTTP API to the existing docs in https://github.com/dessalines/lemmy/commit/c3eaa2273a24093b5d2c78bcb3610a76a6d722c6
