### ISSUE TITLE
Use blur for nsfw image thumbnails instead of hiding.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#438]
```
img {
 -webkit-filter: blur(10px);
}
```

**Comment by dessalines** [comment]
https://stackoverflow.com/questions/13681857/blurring-an-image-via-css

**Comment by richardj** [comment]
Maybe blurring through css filter is not the best option. The support is abysmal and the performance is bad as well. Imagine a whole list if images where the blur needs to be applied.

https://codepen.io/richardj/pen/YzPRKJM

Maybe we use the same kind of technique as Mastodon does, with an extra layer on top and a button that toggles the visibility of the original image.

**Comment by Nutomic** [comment]
Performance seems fine for me based on your link (latest Firefox on Linux). But Mastodon does it another way, which might also be an option for us. Its more complicated to implement though.

https://blog.joinmastodon.org/2019/05/improving-support-for-adult-content-on-mastodon/

**Comment by dessalines** [comment]
Pictshare, our image server, also supports blur: https://github.com/HaschekSolutions/pictshare/blob/master/rtfm/IMAGEFILTERS.md

But I don't wanna use it because as a link aggregator, I still want to allow pictures from other domains. And css blur performance seems okay for me too, I'll start with this way until we find something better.
