### ISSUE TITLE
Automatically update translation report.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#439]
There might be a way using the husky pre-commit, checking for any changes in the translations folder, and altering the translation report generator to manually edit the README.

This should have a good method to replace text between markers: https://github.com/jonschlinkert/markdown-toc

https://github.com/jonschlinkert/markdown-toc/blob/master/lib/insert.js

**Comment by Nutomic** [comment]
Why not #387?

**Comment by dessalines** [comment]
Couple reasons:

- I **really** don't like relying on external services. This is entirely self-contained, in git. Plus I already built this.
  - Means that the backend, front end, and any apps could potentially use and reference these files.
- I don't know if that can handle proper i18n interpolations. Things like `number_of_users: {{count}} users`. 
- Anything that comes out of that would have to be pulled down, and translated into typescript files manually. Not sure what kind of work that would entail. Also seems like it'd have to be a cron-job, since now the repo would be unaware of what translation changes people are making, as opposed to PRs which notify us right away.

**Comment by Nutomic** [comment]
Oh you wrote your own format for translation files? I hope thats not gonna bite us in the ass once the number of translations gets too much for us to handle this way.

**Comment by dessalines** [comment]
Its not custom, just following the i18next resource json format : https://www.i18next.com/misc/json-format

i18next has some service they offer too called locize, but ya I wanna minimize the dependencies on proprietary solutions.

**Comment by Nutomic** [comment]
https://docs.weblate.org/en/latest/formats.html#js-i18next

And weblate is not proprietary, we can selfhost it.
