### ISSUE TITLE
'Next' pagination button always showing.

### ISSUE THREAD

**Issue by richardj** [dessalines/lemmy#441]
The `next` button is always showing on the overviews. Should be hidden when there is not enough content to warrant a next page.

**Comment by dessalines** [comment]
I thought about this when doing paging, but if you want the whole (`prev, next, 0 1 2 3 4 last`) you have to have a `totalCount` coming back with every array, and this requires an expensive SQL `select count(*)` query. We have materialized views now where this would be a little faster than they originally were, but its still significantly slower to have to do that for every query.

One quick workaround that I can do, is only show next when the arraySize = fetchSize .

**Comment by richardj** [comment]
So that is basically checking if the amount of posts is `> amountToBeShownOnPage`? 

With that quick workaround in place we could have empty state page templates as well. This will give the user the options of what can be done.

**Comment by dessalines** [comment]
> So that is basically checking if the amount of posts is > amountToBeShownOnPage

Well, postsShown = postFetchAmount. I don't know the actual amount of posts without a select count query.

> With that quick workaround in place we could have empty state page templates as well. This will give the user the options of what can be done.

That does exist for the front page, and community page, it'll say no posts. The post page it looked cleaner when I just didn't show the sidebar or anything when there were no comments.
