### ISSUE TITLE
Number of replies doesn't increase once it reaches 20

### ISSUE THREAD

**Issue by methylprednisolone** [dessalines/lemmy#447]
Greetings,

I rarely bother to reply to comments directly form the inbox, as such I rarely access it, thus they accumulate indefinitely, and I noticed that after the number replies had reached 20 it stopped growing even though I was getting new replies, just the old replies started disappearing.

A very minor issue, but it would nice to have >20 replies, for example in cases where you're not logged in for long periods of time.

**Comment by dessalines** [comment]
It's just an indicator because its not fetching more than 20 unreads, due to paging. I could add a plus there or something I suppose. There's also an easy to click mark all as read button.
