### ISSUE TITLE
create_post endpoint doesn't support input prefill for title.

### ISSUE THREAD

**Issue by Granitosaurus** [dessalines/lemmy#448]
`create_post` endpoint __does__ prefil `url`, `community` and `body` keywords but it doesn't do that for `title`.

Example:

* custom body: https://dev.lemmy.ml/create_post?body=hello-world  
* custom url: https://dev.lemmy.ml/create_post?url=http://cats-are-lame.com     
* custom community: https://dev.lemmy.ml/create_post?community=python  
* ✗custom title: https://dev.lemmy.ml/create_post?title=IHateCamelCaseButSure

**Comment by Granitosaurus** [comment]
Actually playing around it seems that it does support it but under key `name` rather than `title`!

e.g. https://dev.lemmy.ml/create_post?name=IHateCamelCaseButSure

Maybe this should be refactored :)

**Comment by dessalines** [comment]
Good catch, thx!
