### ISSUE TITLE
Impossible to save settings without entering password

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#451]
To reproduce:

1. click on your username in the top right
2. change a setting (eg language)
3. click on save

Result:
You get an error dialog `Passwords do not match`. The setting is applied, but after reloading the page, it is gone again. It shouldnt be necessary to enter your password for a basic setting change like this.

Maybe we also need to move the settings to a seperate page, because the sidebar is already getting to small for that.

**Comment by dessalines** [comment]
I'll take a look.

**Comment by dessalines** [comment]
I can't replicate this, but I think I know what's going on. You might have some kind of password filler, that's filling some of those boxes. Make sure those three password fields are empty. Otherwise we need to come up with some way I can recreate this bug.

**Comment by Nutomic** [comment]
Oh you're right, removing the prefilled password fixes the problem. But its still something we should fix, because a lot of people use the auto-fill password feature.

**Comment by dessalines** [comment]
That's a tough one, because I have to assume that if you've entered something into that new password field, it's because you want to do a password change, and then the other fields are required too. 

Since it's an optional field, the only way I can really check, is if that box is left empty.

**Comment by Nutomic** [comment]
I think other sites make a seperate submit button for the password change for this reason. Or even put the password change form on a seperate page.

**Comment by dessalines** [comment]
As more settings get added, the user settings might have to have its own page, and different things broken out. I'll leave that to a later ticket.
