### ISSUE TITLE
Limit image height when too tall.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#455]

**Comment by dessalines** [comment]
@Nutomic I found a way to do this, but it doesn't look that great, since in some of the really tall meme templates you wouldn't be able to read anything:

![](https://i.imgur.com/Ko4FyQ5.jpg)

**Comment by dessalines** [comment]
I'm not sure what to do about this one.

**Comment by Nutomic** [comment]
If the image is bigger than the screen, use a single click to maximize it and show it in real size? Or open an overlay that shows the image.

**Comment by dessalines** [comment]
The single click is its expanded view from a thumbnail.

I'll just limit the height to `90vh` for now, if someone wants the high res, it can just be a view image right click.
