### ISSUE TITLE
Look into replacing window alerts with toastr

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#457]
https://github.com/CodeSeven/toastr
https://github.com/apvarun/toastify-js

**Comment by dessalines** [comment]
Tried one, and I love it.

**Comment by Nutomic** [comment]
Yep, looks good!

**Comment by Nutomic** [comment]
How about moving the alert down a few pixels so it doesnt overlap with the username and inbox button on the top right? On desktop that is.

**Comment by dessalines** [comment]
I could change the position to center, that's how it looks on mobile anyway. https://github.com/apvarun/toastify-js#documentation

Would that work?

**Comment by Nutomic** [comment]
You mean top left? That also sounds annoying. Would be better to put it somewhere without any content if possible (meaning the empty bars left and right of the content, below the header).

**Comment by dessalines** [comment]
Toasts are an overlay, I can only do the positions in those docs.

**Comment by Nutomic** [comment]
No margin? Thats annoying then. Bottom right or bottom left would be fine on desktop though.

**Comment by dessalines** [comment]
K, trying bottom left now.
