### ISSUE TITLE
Allow posters to recover from a false positive on the slur filter.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#463]
Based on this Mastodon post: https://mastodon.social/web/statuses/103506030565676658

There is a problem where if the slur filter detects a problematic word, it just won't let the post go through. However, any content filter is bound to have false positives, and if there was no way to sidestep the filter in case of a false positive, then the user experience is severely degraded. We should think about a way for a poster to submit a post with slurs detected for review. Perhaps by the community's moderators, who can approve the post if there indeed was a false positive.

**Comment by StaticallyTypedRice** [comment]
Another idea would be to use the same method used by many subreddits. Where if a slur filter is triggered, the post is allowed to be submitted but immediately removed, and the moderators can then come in and approve false positives, either by an automatic message in the moderation queue or only if the user wants to appeal the removal.

**Comment by StaticallyTypedRice** [comment]
I've moved the issue to yerbamate.dev: https://yerbamate.dev/dessalines/lemmy/issues/17

**Comment by StaticallyTypedRice** [comment]
I've also mirrored this issue on yerbamate.dev: https://yerbamate.dev/dessalines/lemmy/issues/17

**Comment by dessalines** [comment]
What I'll do for this is attempt to return a list of the matched words in the error message. 

For comments, it just replaces the content with *removed*, but for posts, usernames, and community creation, it's a hard stop.
