### ISSUE TITLE
Also list how many votes have been cast in an instance.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#469]
In the homepage, we already have the stats about the total number of posts, comments communities and users. It'd be interesting to see how many total votes (and also up and down votes) have been cast too. Mainly because I think it'd be interesting to see this metric.

**Comment by dessalines** [comment]
This wouldn't be that useful, especially since new comments / posts are automatically upvoted. So really it'd just similar to the number of comments + posts without telling you anything more about engagement.
