### ISSUE TITLE
Test server and Ansible

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#474]
Some items related to this:

- [x] fix existing ansible playbook
- [x] add uninstall playbook
- [x] move data from `/var/lib/docker/volumes`/ to `/lemmy/volumes/` for easier administration
- [x] deploy directly from the local git repo
- [x] configure and test automatic mail relay configuration (#473)
- [x] automatic setup on fresh deployment (#404)
- [x] run multiple instances on the same server (because lemmy needs very few resources)
- [ ] import some test data, eg from dev.lemmy.ml?
- [ ] setup automated performance tests?

**Comment by Nutomic** [comment]
@dessalines what was the thing you mentioned about loading the initial configuration directly into postgres?

**Comment by dessalines** [comment]
You could set up a lemmy from scratch, add some test data, do a db dump using like `docker exec -it dev_lemmy_db_1 > dump.sql ....` I forget the commands to dump and restore rn. Stick that `test_dump.sql` in the repo somewhere.

Then as part of a test deploy, run the postgres command to import that data into the docker db.

**Comment by Nutomic** [comment]
You think that is stable enough to use for production? 

Btw I made a new PR on Gitea.

**Comment by dessalines** [comment]
It def should only be used for setting up test instances, never for production.

**Comment by Nutomic** [comment]
It would definitely be nice to have something like that thats good for production use. Also I should have asked this in #404....

**Comment by dessalines** [comment]
By automatic setup you just mean all the stuff in #404 ? Because that will only fill that site table, it won't create any test comments or anything.

**Comment by Nutomic** [comment]
Yep thats what I mean. Not sure if it actually makes sense to auto-create posts or comments.

**Comment by Nutomic** [comment]
@dessalines Guess I can also do the change for running multiple instances on one server now, so we have all the docker-compose related changes in the same release.

**Comment by dessalines** [comment]
That'd be a good idea.
