### ISSUE TITLE
Site-wide list of most recent comments (or posts with new comments)

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#480]
This would be useful because right now, most of the "hot" posts dont have any comments at all. It would allow finding the posts with actual comments, and joining the discussion. Besides, it could also make it possible to revive discussions on older posts.

For the moment, it would be enough to simply show a list of the latest comments (site-wide), or the posts where those comments were made.

**Comment by dessalines** [comment]
This is also part of #445 since I'm going to eliminate recurring fetches, and have the comments stream via websocket into all users who are on the community (or main) front page.

**Comment by dessalines** [comment]
Some todos:

- [ ] Add a subscribed column to comment_view.
- [ ] Refactor post and comment query builder to work similarly based on attrs.
- [ ] Not just new posts, but new comments are now going to be an all / community push.
- [ ] Make sure it works for community.
