### ISSUE TITLE
Provide a link preview for Mastodon

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#481]
When posting a link, Mastodon shows a small box with title and image from the link. This is probably the same system that is used by Twitter, Facebook etc. I'm sure there is some kind of standard for this but I dont know what its called.

[Lemmy link on Mastodon](https://radical.town/@felix/103563495208387845) (no preview at all)

[Reddit link on Mastodon](https://radical.town/@felix/103563505462496656) (preview text with default icon)

[Peertube link on Mastodon](https://radical.town/@felix/103563516654293889) (preview image and embedded video player)

**Comment by dessalines** [comment]
This is related to the fact that lemmy is a single page app, and it fetches data and fills the page after the initial page load, so it makes it impossible to scrape or get correct page headings and such from. 

I've tried several times to do an isomorphic app: #226 , but frankly its a ton of work for not very much benefit at this point. Its still on the table, but wayyy on the backburner.

The oembed stuff (for example for doing proper twitter / or peertube) embeds to be figured out, and might require hosting iframely or something: #74 #471 . I'm not sure the best way to do that and could use some help on it.

**Comment by Nutomic** [comment]
Oh sorry I didnt realize that you opened basically the same issue just two days ago. Thats why issue descriptions are good, so others know what you are talking about :p

**Comment by StaticallyTypedRice** [comment]
> The oembed stuff (for example for doing proper twitter / or peertube) embeds to be figured out, and might require hosting iframely or something: #74 #471 . I'm not sure the best way to do that and could use some help on it.

I highly implore you to enable content embeds (especially for commercial sites like YouTube or Twitter) on an opt-in basis, so users don't get subjected to tracking by those companies on Lemmy if they don't want to.

**Comment by dessalines** [comment]
dup of the stuff above.
