### ISSUE TITLE
Shouldn't the copyright notice reference Lemmy and not the FSF?

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#487]
https://github.com/dessalines/lemmy/blob/eb5dae8429132cdf707c6009bbda3cbd82a16149/LICENSE#L4

Currently it says ` Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>`

Shouldn't it say something like ` Copyright (C) 2020 Lemmy <https://lemmy.ml/>`?

**Comment by Nutomic** [comment]
That is the copyright for the licence text itself, so I'm almost certain its correct like this.

**Comment by StaticallyTypedRice** [comment]
Shouldn't there be a Lemmy copyright notice somewhere in the license file? I can't find it. I know in the MIT license you're supposed to change the copyright notice to reference your project.

**Comment by igalic** [comment]
> ### How to Apply These Terms to Your New Programs
>
>  If you develop a new program, and you want it to be of the greatest possible use to the public, the best way to achieve this is to make it free software which everyone can redistribute and change under these terms.
>
>  To do so, attach the following notices to the program.  It is safest to attach them to the start of each source file to most effectively state the exclusion of warranty; and each file should have at least the "copyright" line and a pointer to where the full notice is found.
>
>```
>    <one line to give the program's name and a brief idea of what it does.>
>    Copyright (C) <year>  <name of author>
>
>    This program is free software: you can redistribute it and/or modify
>    it under the terms of the GNU Affero General Public License as published
>    by the Free Software Foundation, either version 3 of the License, or
>    (at your option) any later version.
>
>    This program is distributed in the hope that it will be useful,
>    but WITHOUT ANY WARRANTY; without even the implied warranty of
>    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>    GNU Affero General Public License for more details.
>
>    You should have received a copy of the GNU Affero General Public License
>    along with this program.  If not, see <https://www.gnu.org/licenses/>.
>```
>
> Also add information on how to contact you by electronic and paper mail.
>
>  If your software can interact with users remotely through a computer network, you should also make sure that it provides a way for users to get its source.  For example, if your program is a web application, its interface could display a "Source" link that leads users to an archive of the code.  There are many ways you could offer source, and different solutions will be better for different programs; see section 13 for the
specific requirements.

some projects simply have a NOTICE file with the above text

**Comment by dessalines** [comment]
I don't want to add this to every file in the project.

And the LICENSE should never be edited. Example: https://github.com/tootsuite/mastodon/blob/master/LICENSE
