### ISSUE TITLE
Use random content IDs instead of sequential ones.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#492]
I've noticed that the Lemmy content IDs are all sequential, so if the last post had an ID of 10, the next one would have an ID of 11. I feel that it really should be random, like the content IDs on Reddit, because sequential IDs are susceptible to being enumerated, and can allow an instance to be very easily scraped for content by running through all the numbers up to the most recent post or comment, and will be disastrous if Lemmy ever plans to have unlisted posts.

This is a relevant Tom Scott video: https://www.youtube.com/watch?v=gocwRvLhDf8

**Comment by Nutomic** [comment]
#399 is basically the same issue. Scraping should already be prevented by the rate limits.

**Comment by StaticallyTypedRice** [comment]
My point is if Lemmy ever implements the ability to unlist or hide posts, this will make it useless. I believe it's also considered bad practice for a modern site to have sequential IDs.

**Comment by dessalines** [comment]
I thought about using hashids, but it didn't really seem necessary yet. And @Nutomic is correct, both the rate limiting, and an auth check for hiding / private posts means that this is a non-issue.
