### ISSUE TITLE
Avatar upload broken with local docker development

### ISSUE THREAD

**Issue by Charleshthomasiii** [dessalines/lemmy#501]
With local docker development, uploading an avatar makes a post request to http://localhost:8536/pictshare/api/upload.php, but the docker default pictshare port is http://localhost:8537. Not sure if I setup my environment incorrectly or how to fix. 

![pictshare](https://user-images.githubusercontent.com/22798606/73677269-dc5d8d00-4683-11ea-82f5-c06a7870ace7.png)
![pictshare2](https://user-images.githubusercontent.com/22798606/73677277-debfe700-4683-11ea-80c4-df3c80f63de7.png)

**Comment by dessalines** [comment]
This is correct, pictshare doesn't work without nginx. 

Here's a sample config: https://github.com/dessalines/lemmy/blob/master/ansible/templates/nginx.conf

**Comment by dessalines** [comment]
As an example of what I do locally I have this in the start of my lemmy.conf:

```
server {
        listen       8535;
        server_name  localhost;
...
``` 

So then I access it at http://localhost:8535

**Comment by Charleshthomasiii** [comment]
How do you have your ssl_certificate and ssl_certificate_key set up in your lemmy.conf?

**Comment by dessalines** [comment]
Added a disclaimer to the readme.

**Comment by Nutomic** [comment]
Fyi this would be fixed with #371.

@Charleshthomasiii you don't need any ssl certs for development.

**Comment by ma-karai** [comment]
ok this is all nice and dandy, but what if people dont use nginx as a reverseproxy, i mean there are a plenthora of different reverse proxies out there. 
HAproxy, caddy, traffik to name some of them. Is there a way to disable avatar upload in general ?

**Comment by Charleshthomasiii** [comment]
I think to use a different reverse proxy you would have to edit several yml files (lemmy/ansible/lemmy.yml, lemmy/ansible/templates/docker-compose.yml, /home/charles/lemmy/ansible/uninstall.yml, lemmy/docker/dev/docker-compose.yml, lemmy/docker/prod/docker-compose.yml).

As for disabling avatar uploading, a quick and dirty way could be to disable it on the front end in lemmy/ui/src/components/user.tsx, although that's not a great solution.

**Comment by Nutomic** [comment]
If you are deploying manually without ansible, the only thing you need to do is write the config for your reverse proxy, based on the nginx config file. And the docker-compose.yml if you use that.

**Comment by dessalines** [comment]
There is no setting for disabling avatars site-wide, and I don't plan to make one. Its a user setting already.

**Comment by ma-karai** [comment]
I completely understand that you don't want to take it away on a side wide basis.
