### ISSUE TITLE
initial db password

### ISSUE THREAD

**Issue by remyd1** [dessalines/lemmy#509]
Hi,

I just followed the docker install section, and I wanted to change the default DB password (which is "password" [see docker-compose](https://github.com/dessalines/lemmy/blob/master/docker/prod/docker-compose.yml#L8) and [lemmy.hjson](https://raw.githubusercontent.com/dessalines/lemmy/master/docker/lemmy.hjson)).

However, it does not work. My nginx returned `502 Bad gateway` (with bad headers in nginx logs `failed (104: Connection reset by peer) while reading response header from upstream, client ...`) and even a curl request on port 8536 is returning `Connection reset by peer`.

```bash
curl http://127.0.0.1:8536/
```

`docker logs` on the `dessalines/lemmy` container is returning :

```
FATAL:  password authentication failed for user "lemmy"
```

So, it looks like the pgsql password cannot be modified. I know this is local (only between the web and the DB container), but if it cannot be changed, it is still, IMHO, unsecured. Am I wrong ?

Thanks,

Best regards,
Rémy.

**Comment by dessalines** [comment]
You changed the password in both places, correct. Both the lemmy.hjson, and the docker-compose.yml?
