### ISSUE TITLE
Possibility: Change post hot rank to use newest comment time, rather than post published time.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#517]
Because of the typical reddit sorting algorithm used here, threads essentially die after a day or two and no one ever sees them again, so the chances of an old thread actually showing up on the front page are none.

On the other hand, letting a new comment bump a really old post, might not be ideal, as someone could just comment on a bunch of old threads and make them show up on everyone's front page.

I'm not sure if this should be done, but it might be a good idea, like a forum, to have the time sort work using `post.published_time or most_recent_comment.published_time`.

```
  (
   case when (p.published < ('now'::timestamp - '1 month'::interval)) then p.published
   else max(greatest(c.published, p.published))
   end
  ) as newest_activity_time 
```

**Comment by Nutomic** [comment]
Why not make a seperate tab next to subscribed and all with recently commented. The dropdown already has too many options lol.

**Comment by dessalines** [comment]
I was thinking this would be a change for the existing hot rank for posts, everywhere.  The new comments thing is #480 , that's different.

**Comment by StaticallyTypedRice** [comment]
> Why not make a seperate tab next to subscribed and all with recently commented. The dropdown already has too many options lol.

We could call it "active" and include all interactions.
