### ISSUE TITLE
Unread message indicator not going away

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#527]
This worked fine before, but now it stays like this even after marking the message as read, and only goes away if I reload the page, or after switching between tabs I think.

![Screenshot_20200210_142437](https://user-images.githubusercontent.com/1044450/74153629-f7db1180-4c08-11ea-8334-c6f140623903.png)

**Comment by dessalines** [comment]
This seems to be an issue not when clicking mark as read on the inbox, but when using the link click (which should count it as read). I planned on refactoring the code that does this anyway.
