### ISSUE TITLE
Ask for confirmation before closing a tab with unsaved data.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#529]
If you go onto websites like Reddit, type out half a post or comment without submitting it and then close the tab (or do anything to unload it), it will ask for confirmation as a measure against losing unsaved data. I've done this with Lemmy where I accidentally closed the submit page and lost the half a post I was preparing.

You're supposed to attach a function to `window.onbeforeunload` in the global scope and implement it such that if the user has entered any text into forms without submitting, return `true` or a string that will be displayed in the prompt. I would personally create a global variable called `hasUnsavedData` or something and set it to true or false depending on if there is unsaved posts or comments in the page, and check or return that. 

I tried taking a crack at implementing this, but it turns out I have no idea how inferno works and couldn't even get the window.onbeforeunload to run in the global scope. Hopefully someone with more react/inferno knowledge can implement this.

**Comment by StaticallyTypedRice** [comment]
Relevant MDN documentation: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload

**Comment by dessalines** [comment]
This is a single page web app, there are no window unloads. There might be a way to properly do this with react style apps tho.

**Comment by StaticallyTypedRice** [comment]
> This is a single page web app, there are no window unloads. There might be a way to properly do this with react style apps tho.

I believe a window unload is still triggered when you either close the tab, switch to a page not in the react app or hit the back button to a page not in the react app.

**Comment by StaticallyTypedRice** [comment]
There is a window unload function that closes all the websockets in this file: https://github.com/dessalines/lemmy/blob/master/ui/src/services/WebSocketService.ts

I tried tacking a `return true;` and a `return "string";` to it but it didn't do anything. Either I'm not doing it right (completely possible) or it outright never gets triggered, which means the websocket operation isn't getting executed either.

**Comment by dessalines** [comment]
It shouldn't get triggered unless you reload the window, which a single page web app should never do.

**Comment by StaticallyTypedRice** [comment]
Still, we should find a way to ask for confirmation on close so users don't lose post or comment drafts.

**Comment by Nutomic** [comment]
@dessalines It happens if you close the tab, which can happen by accident, try Ctrl + W (or Q?) in Firefox.

**Comment by dessalines** [comment]
This might be possible using: 

`const unblock = history.block('Are you sure you want to leave this page?')`

--- 

Another wishlist item here tho, is to automatically **save** your comment on the front end, so that you could potentially navigate around, but then when you come back to the box, it fills it in.
