### ISSUE TITLE
Just a link aggregator? NO!

### ISSUE THREAD

**Issue by lucasdondo** [dessalines/lemmy#530]
When someone posts a link, you can't get into the post's comments, body and more info. That makes no sense.
Solution: Don't open the link just by touching the post's title!

**Comment by dessalines** [comment]
> When someone posts a link, you can't get into the post's comments, body and more info. That makes no sense.

Yes you can. Just click comments.

**Comment by StaticallyTypedRice** [comment]
> When someone posts a link, you can't get into the post's comments, body and more info. That makes no sense.
> Solution: Don't open the link just by touching the post's title!

This is how Reddit works. Clicking on a title takes you to the link.

**Comment by Nutomic** [comment]
I think this is still a useful discussion to have, because its not clear if a link will take you to a discussion on Lemmy or to an external site. Sure Reddit also does it like this, but that doesnt automatically mean its a good idea. It would be good if we could make this more obvious somehow.

**Comment by lucasdondo** [comment]
> > When someone posts a link, you can't get into the post's comments, body and more info. That makes no sense.
> > Solution: Don't open the link just by touching the post's title!
> 
> This is how Reddit works. Clicking on a title takes you to the link.

That doesn't mean that's how this SHOULD be like. Big companies also can be wrong.

**Comment by lucasdondo** [comment]
> > When someone posts a link, you can't get into the post's comments, body and more info. That makes no sense.
> 
> Yes you can. Just click comments.

What is there are no comments?

**Comment by richardj** [comment]
Personally i don't like this, or what Reddit does. But that is a personal opinion. What could be done is that with external link you add a external link symbol to it? 

https://image.flaticon.com/icons/svg/25/25284.svg

**Comment by dessalines** [comment]
> Personally i don't like this, or what Reddit does. But that is a personal opinion. What could be done is that with an external link you add an 'external link symbol' to the title, visually telling the user that.

At first, I had it exactly like that, but a lot of ppl complained that when they were clicking the link, it wouldn't actually go to the link, just the comments, and that symbol was harder to find.

**Comment by dessalines** [comment]
One thing I would consider, is making the comments not `text-muted`, but look like a link. It wouldn't be as clean looking, but might be more clear.

**Comment by richardj** [comment]
What Reddit does right now it seems, is that links go to the discussion page (or comment page), and it will show the link / source beneath it. 

![Screenshot 2020-02-14 15 29 05](https://user-images.githubusercontent.com/474024/74539694-c7fc7880-4f3e-11ea-80d3-681a2c45452c.png)

This would help with two things:
1. you can always go directly to the source
2. you can always go directly to the comments.

**Comment by dessalines** [comment]
Hrm, I do have that simplified URL go to the real link, I suppose I could have the main one always go to the comments. But someone complained about that originally so I have no way to gauge which one is more preferred.

**Comment by richardj** [comment]
Maybe start it off simple and go from there, you could run and implement A/B testing software to see which one is more preferred, or it can become a setting at some point. 

For now maybe having the user choose from the overview what they want (title goes to comments, link, if applicable shown beneath that) is at least in that way standardized.

**Comment by dessalines** [comment]
Okay, for now I'll change it to always going to comments.

**Comment by Nutomic** [comment]
Reopening this because its a useful discussion to have. I will also rename the "question" label to "discussion".

**Comment by StaticallyTypedRice** [comment]
One suggestion: Place an outgoing icon on all outgoing links, Wikipedia does this.

https://en.wikipedia.org/wiki/Help:External_link_icons#Example (See the example links column)

**Comment by Nutomic** [comment]
@StaticallyTypedRice Its not the most beautiful icon, but I agree that it would help to clarify the behaviour. We should give it a try.

**Comment by StaticallyTypedRice** [comment]
> @StaticallyTypedRice Its not the most beautiful icon, but I agree that it would help to clarify the behaviour. We should give it a try.

I don't think we can use the WIkipedia one, but I'm sure there are Creative Commons icons we can use. Maybe import an icon set like FontAwesome while we're at it.

**Comment by dessalines** [comment]
That's easy enough to add.
