### ISSUE TITLE
Explain sorting methods on the frontend

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#532]
Right now we have three sorting methods for posts and comments (hot, new, best with different time parameters). For someone who doesnt know Reddit, this doesnt seem obvious at all. We should highlight this option a bit more, and add a short description for each sort method. 

This would also allow us to experiment with more different algorithms, like the reddit algo that is good for new posts, our new algo which is good for discussions, the hackernews algorithm, and others. Users can then decide on a case by case basis which one they want to use.

**Comment by dessalines** [comment]
I can't think of a good place to put this, it would probably be too cluttered to add it here.

![](https://i.imgur.com/o1D5O1B.png)

I mainly want the site to be simple enough to use to not need any instructions.

There's also already the docs link at the bottom, I'd be willing to add a page describing the sorts there.

**Comment by Nutomic** [comment]
I think we will have to redesign that entire area, the stuff in your screenshot is quite cluttered already.

**Comment by dessalines** [comment]
I could turn the Posts vs Comments, and All vs Subscribed into dropdown selects instead of radio buttons, it might be cleaner.

**Comment by Nutomic** [comment]
Tabs could work. And we could put little popups with the explanation like peertube does it.

**Comment by dessalines** [comment]
@Nutomic what about a hover / press and hold on the sorting box? 

If not that (since it may require too much space), maybe a question mark beside it, that links to a section of the user guide where we can explain the sorting?

**Comment by Nutomic** [comment]
Cool!
