### ISSUE TITLE
Unable to access https://dev.lemmy.ml/

### ISSUE THREAD

**Issue by Mxchaeltrxn** [dessalines/lemmy#547]
### Expected
Page opens and displays regular content.

### Actual
I'm unable to open the page.

I'm actually trying to get to the contributing guidelines (https://dev.lemmy.ml/docs/contributing.html) but that shows the same thing. 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/34886045/74706557-65bbb480-526b-11ea-8995-189ad7f632b4.png">

**Comment by Nutomic** [comment]
Works fine here. Can you try a different browser, different device etc?

**Comment by Mxchaeltrxn** [comment]
@Nutomic Strange. It seems to work on Tor but not on Firefox or Chrome. I couldn't open it on my phone either but my phone browser does that sometimes (not sure why). 

This is a good enough way around the problem for me so feel free to close it.

**Comment by Nutomic** [comment]
Yeah it seems the problem is on your side. Maybe try over a different internet connection or with a different DNS server.
