### ISSUE TITLE
Adding admin setting panel/page

### ISSUE THREAD

**Issue by remyd1** [dessalines/lemmy#550]
Hi,

It would be great to have an admin page to validate user or community registrations, ot to edit some lemmy configurations like email general settings. Maybe I missed something, but the API is not really user friendly...

Best,

**Comment by dessalines** [comment]
Most of the admin settings (such as setting up email) are done through the lemmy.hjson file.

https://dev.lemmy.ml/docs/administration_install_docker.html

A few (such as disabling registrations, or editing your main sidebar) can be done by clicking the edit on the sidebar when you set up the site.

You should never have to use an API to change settings.

**Comment by remyd1** [comment]
Ok !

> A few (such as disabling registrations, or editing your main sidebar) can be done by clicking the edit on the sidebar when you set up the site.

Yes, I saw that ! However, in certain circumstances, you need to private registrations (eg: with invitation links) or prior moderation. That would be great to have these kind of features.

Thanks,

**Comment by dessalines** [comment]
At some point we're gonna add an optional sign up request layer: #209
