### ISSUE TITLE
smtp server configuration in lemmy.hjson

### ISSUE THREAD

**Issue by remyd1** [dessalines/lemmy#551]
Hi again,

The `lemmy.hjson` file requires a username and a password to authenticate and send emails.

However, my server host is able to send emails without the need of user/password (using "Internet"/code configuration with postfix (see bellow)).
The configuration is done following this howto : https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-postfix-as-a-send-only-smtp-server-on-ubuntu-16-04

Thus, if I does not fullfill the user/password in `lemmy.hjson` the lemmy container restarts all the time...

Best regards,

**Comment by dessalines** [comment]
This is actually set up by default in the ansible deploy:

- lemmy.hjson :  https://github.com/dessalines/lemmy/blob/master/ansible/templates/config.hjson#L9
- docker-compose.yml : https://github.com/dessalines/lemmy/blob/master/ansible/templates/docker-compose.yml

Then all you have to do is name your vps the same as your server (reverse dns).

**Comment by remyd1** [comment]
Ok, I will check that !

Thanks !

**Comment by dessalines** [comment]
Let me know if this needs anything else.
