### ISSUE TITLE
Remove the thumbnail or display a placeholder image if the image fails to load.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#553]
Some websites have hotlinking prevention which, well, prevents the hotlinked thumbnail in Lemmy from being displayed. Reddit seems to do this. When this happens, you just get your browser's standard "broken image" icon in place of the thumbnail, which kind of ruins the look of the page. It'd be good to detect when an image fails to load and automatically remove the thumbnail or display a generic placeholder thumbnail in its place.

**Comment by StaticallyTypedRice** [comment]
Or, we could think about proxying thumbnails through the server to prevent external websites from tracking users in Lemmy via thumbnail embeds.

**Comment by dessalines** [comment]
Its only an `<img`, not an iframe / html embed, I've never seen anything that says that can track you.

**Comment by StaticallyTypedRice** [comment]
> Its only an `<img`, not an iframe / html embed, I've never seen anything that says that can track you.

It will send a minimum of the IP address, HTTP request headers, and a referrer linking back to the page the request originated from.
