### ISSUE TITLE
Use image thumbnails

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#555]
As someone in the Matrix chat noted, Lemmy doesnt use any actual thumbnail images, but instead loads full-sized images and resizes them in html to use as thumbnails. This means that the website uses a lot of data that might not actually be needed. Loading the front page of dev.lemmy.ml can take 5 MB for this reason.

We should change this behaviour so that actual thumbnails are used, and we dont waste bandwidth.

Edit: According to Chrome dev tools, the main page also loads oembed for each external URL, even though embeds arent used on the main page at all.

**Comment by StaticallyTypedRice** [comment]
> We should change this behaviour so that actual thumbnails are used, and we dont waste bandwidth.

This typically requires requesting the image from the server side when the link is posted, resizing using an image library, and permanently storing the thumbnail or re-requesting the original image and re-processing it once in a while to keep it updated.

**Comment by dessalines** [comment]
Here's the pictshare endpoint: I really don't want to change the post table to add a thumbnail url column.
