### ISSUE TITLE
Make RSS files statically indexable.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [dessalines/lemmy#559]
Based on this Mastodon post: https://mastodon.social/web/statuses/103733299615213861

Currently, RSS feeds on Lemmy can only be accessed through the single page webclient, which we already know is not very compatible with web crawlers. This will kill our discovery rates on RSS finders like [Fraidycat](https://github.com/kickscondor/fraidycat). It would be a good idea to somehow link to the RSS files in a way that does not need the single-page web app so they can be indexed.

**Comment by dessalines** [comment]
No, lemmy has static rss feeds: https://dev.lemmy.ml/docs/contributing_websocket_http_api.html#rss--atom-feeds

**Comment by StaticallyTypedRice** [comment]
> 
> 
> No, lemmy has static rss feeds: https://dev.lemmy.ml/docs/contributing_websocket_http_api.html#rss--atom-feeds

Static yes, but not discoverable unless the web app renders properly, which web crawlers struggle with.

**Comment by dessalines** [comment]
Crawling / archiving / SPA stuff is a separate issue, that's #347

**Comment by Nutomic** [comment]
Do we even need a full isomorphic app for this? For the RSS feed discovery you only need an HTML header (afaik), so it should be enough to insert that into the base HTML template, without implementing SPA completely.

**Comment by dessalines** [comment]
Unfortunately yes, because depending on the page, you might be looking at a community rss, an all rss, a subscribed rss, or a user rss.

**Comment by Nutomic** [comment]
I know, so if we serve the index.html through Rust, we can just insert the RSS link in there, without modifying anything else.

**Comment by dessalines** [comment]
Getting RSS feeds to me is much less important than the other crawlable things. Even page title doesn't come till after the bundle load for example... all of these need a proper isomorphic app.
