### ISSUE TITLE
Long threads take very long to load

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#577]
I noticed that [this thread](https://dev.lemmy.ml/post/30924) takes extremely long to load (around 40 seconds on my laptop in a manual measurement). During this time, it also blocks user input during loading (looks like it doing work on the main thread). This is definitely not acceptable and needs to be much faster if we want to be able to deal with threads with 100 or 1000 replies.

**Comment by dessalines** [comment]
Hrm.... I'll have to pull this down and benchmark it to see what's going on. Might be a few days to fully get to it.

**Comment by Nutomic** [comment]
Big user profiles are also very slow to load (eg your profile). Seems like the frontend is processing the entire post history or something like that.

**Comment by Nutomic** [comment]
Also I'm jealous because you have way more points than me lol. Have you ever thought about removing that? Seems like a bad incentive really.

**Comment by dessalines** [comment]
Hrm you're right its not a DB thing, its front end. My damn tippy / tooltip library.
