### ISSUE TITLE
editing history

### ISSUE THREAD

**Issue by koalp** [dessalines/lemmy#580]
I think it would be nice to be able to add an editing history/diff for posts and comments, to be able to see if someone completely changed their comment or removed some content that answer are referring to.

I also think it's not a problem if someone really made a mistake (like leaking information they don't want to show), because they could always delete their comment.

**Comment by dessalines** [comment]
> I think it would be nice to be able to add an editing history/diff for posts and comments, to be able to see if someone completely changed their comment or removed some content that answer are referring to.

I really disagree with this, if someone changes their comment, its them telling everyone they explicitly don't want everyone else to see that previous version.

**Comment by koalp** [comment]
Thanks for your answer. I proposed it because sometimes it can be confusing to read answers that are not related to the message because it have been modified. And if someone had written something they really wanted to hide I think they could have deleted it. 
And if there would have been a series of small modification it could have been grouped together.

But I understand that it could reduce the freedom of mind of people if they know they will not be able to hide the previous version of their message.

Anyway, **it would maybe be nice to create a "wontfix" tag for issues that won't be fixed**, what do you think ?

**Comment by Nutomic** [comment]
I think it might be necessary to have a feature like this to prevent abuse. Like someone attacking another user, and removing the attack via edit before a mod can see it.

@dessalines yes please tag all issues :)

**Comment by StaticallyTypedRice** [comment]
I agree with @dessalines on this. The right to be forgotten is a monumental part of a privacy oriented social media platform. IMO there are more legitimate reasons for wanting a previous comment lost to history than there are malicious reasons. Accidentally posting personal information is a big one. Not wanting to be "datamined" through your post/comment history is another.

If we *were* to implement an edit history, we would *at the very least* need a way for the user to delete all the content associated with the post or comment *from the server*.
