### ISSUE TITLE
New comments sometimes clearing out other user's comment forms.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#588]
Sometimes new top level comments clear out other users comment forms. This has to do with the buildCommentsTree(), (which replaces / unmounts the other components on a new comment addition).

This should be moved to `comment-nodes.tsx`, and possibly do recursion based on the react nodes, not the comment objects, so as to preserve their state.

**Comment by StaticallyTypedRice** [comment]
I've experienced the same problem with private messages.
