### ISSUE TITLE
Abstract views to cover both activitypub and DB types.

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#595]
The front end right now is receiving DB views like `CommunityView`, but it needs to handle activitypub types too.

This means a folder with additional types, which can convert from the APUB -> front_representation, and DB -> front_representation.

#578

**Comment by Nutomic** [comment]
I believe this also means that we have to handle search, sorting and so on without sql, cause apub objects will not be stored in the database.

**Comment by Nutomic** [comment]
@dessalines How do we go about implementing this? Right now my federation code is a bit messy, basically I am redirecting API calls inside websocket/server.rs, which I should probably moving into the api, but that already has a shitload of code (api/community.rs has 600 loc). Any chance we can split that up some other way?

**Comment by Nutomic** [comment]
Turns out we dont need this because we are writing data directly into the DB.
