### ISSUE TITLE
Mirror remote communities

### ISSUE THREAD

**Issue by duck57** [dessalines/lemmy#599]
I'll try to explain by an example.  I'll be the admin of `percussion.tk`, an instance primarily for drummers and other percussionists.  `rabbits.org` will be a remote instance filled with house rabbit lovers.

## Simple Mirroring

My users have asked me to mirror `rabbits.org/c/assicalmusic` because percussion.tk has a large presence on rabbits.org's classical music community and it's representative of our classical music discussion.  Once mirroring is set up, `percussion.tk/c/assicalmusic` is identical to the community on rabbits.org, including moderators and their decisions.

In tl;dr form, a remote community is mirrored locally and added to the instance front page as if it's local.

Is this similar to what is discussed in #578? 

## Name Collisions

In spite of being intended for drummers, `percussion.tk/c/horses` is a highly active discussion forum for the care of horses with a focus on show jumping.  `rabbits.org/c/horses` is mostly focused on horse pictures.  Both instances wish to mirror each other's equestrian community but do not want to rename or otherwise move their current community.  They can still mirror each other under new community names, such as `rabbits.org/c/showjumping` and `percussion.tk/c/ponypics`.

## Multi-level requests

If `moose.dewlap` wishes to mirror `rabbits.org/c/showjumping` from the above example, they will be notified that it really is `percussion.tk/c/horses` and may proceed to mirror from the source as usual.

## When things go wrong

I foresee two ways in which mirroring can go wrong:

1. The source instance going down
2. Incompatible rule change or enforcement from the source instance

Rogue admins and mods can cause either of the above, but these situations can arise with no malice involved by any party.

If being mirrored no longer suits the needs of your instance, you may make a one-way decision to break the mirror.

Once the mirror has been broken, an automatic un-deletable notification post will be made to your new local community copy with an optional field to explain why you chose to break the mirror.  The local admin may then appoint new moderators or leave the local community in a frozen unmoderated state (no new posts may be made until mods are chosen).  To handle rogue moderators, moderation deletions in the past 7 days may be reverted by the local admins or new local mod team.  However, any older moderation deletions that were mirrored over are permanent.

### Incompatible Rule Change Example 1

We're mirroring rabbit.org's /c/furries and they change the rules to allow NSFW content.  `percussion.tk/c/furry_nsfw` already exists, so the mirror is broken.  Additionally, the moderators of `rabbit.org/c/furries` have been deleting posts from percussion.tk users arguing against the rule change.  After the mirror is broken, the newly-minted mods of `percussion.tk/c/furries` delete any remaining NSFW posts and restore the posts arguing against the rule change as their documentation for why they broke the mirror.

### Rule Change Split Example 2

Rabbit.org decides that they will no longer allow memes on `rabbit.org/c/assicalmusic` because they have made `rabbit.org/c/classicalmemes`.  The percussion.tk admin team decides to break the mirror after their local users tell them they are opposed to the rule restriction.

### Remote Server Down

moose.dewlap decides to shut down.  I've been mirroring `moose.dewlap/c/happy-hardcore`.  After a specified duration without any contact with moose.dewlap (or after receiving an instance deletion message), percussion.tk automatically breaks the mirror.

### Moderator & Community

* Allow mirroring: yes/no/with approval?  Yes and no will automatically accept or reject incoming requests to mirror.  `with approval` sends them to a queue for moderator review.

### Admin & Server

* Communities may be mirrored: yes/no?
* If yes, set defaults for all the community mirroring options
* Time with no interaction other servers should wait before they assume your instance is gone for good.  Suggested hardcoded minimum of 4320 minutes (3 days) and a maximum of 69420 minutes (42 days, 5 hours).  This is assumed to be set once and sent as part of initial handshake when establishing a federation.  If the remote server's timeout is outside the hard limits, set it to the nearest hard limit in the database.
* Following from #236, who may create new mirrors?  With admin review required, outgoing requests for a new mirror are queued for admin approval or modification before being sent.  Going back to the /c/horses example above, if one of my users mirrors `rabbit.org/c/horses` to `percussion.tk/c/horse2` and I have admin approval on, I may say that the local community name will be /c/ponypics before sending the request to rabbit.org

This section is notably longer than the community settings because it would be instance admins who set up new mirrors and break incompatible ones.

## Open Questions

* After an intentionally-broken (eg. due to moderation incompatibilities) mirror, do your local subscribers follow only the new local community or do they follow both the new community and the original?
* After a broken mirror from a downed server, does the new local community get placed in an "unmoderated communities" queue for the local admins and frozen or does the local admin team default as the new moderators until they select the real mods?  Should this just be a server setting?
* Hardcoded timeouts were picked to be somewhat reasonable times for getting a low-traffic server back online after an SSL cert expires, for example.
* Moderation deletion undo time was picked as a reasonably generous amount to detect the incompatible moderation, break the mirror, and then set up under local rules.  It should be long enough to mitigate problems when they're not immediately apparent and short enough that it cannot be abused as an unlimited undelete.

**Comment by Nutomic** [comment]
I didnt read your whole text, but it sounds like you are essentially talking about activitypub federation. That is what we are working on right now. It will take time to reach the initial implementation though, and until then, we wont know how things like moderation etc will work. So be patient.

**Comment by Nutomic** [comment]
Closing this because its really too general and its not clear what we can do here. If you want to contribute towards our ActivityPub implementation, I suggest you read the spec and other documentation, and have a look at our [code](https://yerbamate.dev/dessalines/lemmy/pulls/27/files).
