### ISSUE TITLE
avatars look unnecessary and they break the minimalist theme, IMHO they should be removed

### ISSUE THREAD

**Issue by DontUseGithub** [dessalines/lemmy#600]
**In this issue I'm only referring to avatars on pages other than the user's.**

Reddit is great because it's not about who you are but instead it's about what you say. Reddit isn't yet another social media because of this. And I think lemmy should keep this legacy principle as well. That aside, even design-wise I don't think they look good. If you don't agree on removing them, then you could try to make them smaller, maybe this will make them look better.

**Comment by pioneer** [comment]
No, I don't think they look unnecessary, they look great IMO. However, seems there will definitely be many opinions on that. I've always been a fan of configurability, so the best can be done is to introduce an option whether to show avatars or not.

**Comment by dessalines** [comment]
@DontUseGithub there is already a user setting to hide avatars.
