### ISSUE TITLE
On mobile, show notification indicator without opening menu

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#607]
It would be nice if there was a notification icon next to the menu button, so I don't have to click it if I want to check for new notifications.

Besides, we could maybe show a popup and even play a sound when a new notification arrives. It is live updating after all.

**Comment by dessalines** [comment]
I can see if its possible to always show the bell beside the collapse menu, that'd be nice to have.

There are browser notifications already, but I could also add an in-app toast. I'll play around with it a bit.
