### ISSUE TITLE
‘Inbox’ mades me expect to see direct messages

### ISSUE THREAD

**Issue by muello** [dessalines/lemmy#608]
Just signed up, started playing around, and then got a notification. Clicked on the bell and discovered the ‘inbox’. A bit confusing: it took me a while to work out that the notification was not in fact a direct message but a comment on a thread I'd participated in.

Ideas for improvement:
* instead of seeing ’Inbox for <user>’, perhaps the user should see ‘Notifications for <user>‘ or something along those lines.
* isn't the replies/mentions/messages menu conceptually more fundamental from the other two? At least, that'd be one way to see it. In which case functionally separate it out. Cf. mastodon notifications bar: all/mentions is the most obvious alternative, while other filters are hidden away in a menu behind a smaller botton.

**Comment by dessalines** [comment]
> was not in fact a direct message but a comment on a thread I'd participated in.

It was not just a random comment, is a was a comment reply **to your comment**, IE a direct reply to you. Reddit also notifies you for direct replies.

In a public commenting platform like this, direct messages are much more common than private messages. 

> isn't the replies/mentions/messages menu conceptually more fundamental from the other two?

I'm not sure what you mean. The inbox shows all things you should be notified of: the replies, user mentions, and private messages. Why should it not show any of those?

**Comment by muello** [comment]
Sorry, I wasn’t as specific or as clear as I could be.

Yes, I worked out that it was a reply to my comment and that what I was looking at was a list that included direct replies.

I’m familiar with the idea of direct replies from various platforms – I expect nearly everyone by now is. But my first guess was wrong: I assumed I was looking at a list of just private messages.

I’m not suggesting that the inbox shouldn't include all things a users gets notif for. I’m thinking about the way the options in the menus are presented. 

Currently there are three, they're apparently coordinated in terms of their importance (not in any obvious hierarchy: they're all the same size, etc.), and they're menus. When you first see a menu and you only see one of its options, and it's not otherwise labelled, immediately seeing and recognizing what you're looking at can be quite an unlikely outcome.

My "hierarchy" suggestion is based on the Masto column design (in the web interface): take for example replies/mentions/messages/all as the fundamental distinction. Make that one obvious, visually fundamental, meaning: make it so you can see all four of those options at a glance, like radio buttons or something. (Masto has just all/mentions, and they're presented side by side.) Meanwhile keep the other two filters in menus, but label them, or make it so that the default setting gives a good immediate clue to what the choices are.

Think about the naive user, which in this case I was. On my first view, I saw three menus controlling three different filters. But I didn't recognize them for what they were, they aren't really labelled. So my main clue was "inbox". This is perhaps not universal, but for me the paradigm of an inbox is an email inbox, which I think of, probably inexactly, as mainly containing, roughly, "private messages". So my first guess, which i voiced to my partner in communication, was wrong. I then spent a while puzzling over the icons below it, wondering, for example, why there would be up and down-vote arrows on a private message, which was the first clue that set me on the right track.

I guess my thought was that first impressions are important in determining the uptake of a platform, so I wondered whether it would be possible to design the inbox in a way that made confusion of the sort I experienced less likely.

**Comment by dessalines** [comment]
I agree it'd be nice to have labels for all the selects ( rather than have them in the select menus as I do now). For example there's a sort select on the front page, that you don't know exactly what it is until you select it.

![image](https://user-images.githubusercontent.com/930215/77196194-3c37b800-6ab9-11ea-8ecc-35503b19a7eb.png)

It looks like bootstrap has an input-group-prepend that might work for this:

![image](https://user-images.githubusercontent.com/930215/77196276-61c4c180-6ab9-11ea-8ffe-97fc48a62d30.png)

My worry is that these might take up too much space, but I'll test it out.

I'd rather not do a radio button groups (see the filters on the front page for example) for all the selects (I only do this for a few, with small numbers of options), and because on that page all the other filters are `<select>`s.

**Comment by dessalines** [comment]
On second thought I'd consider doing a radio button group for the Unread and Message Type, but leaving it alone for sort. It'd probably look better anyway, and that's not too many options.
