### ISSUE TITLE
Problem with Ansible installation

### ISSUE THREAD

**Issue by cloned1** [dessalines/lemmy#615]
Hello.

I was unable to finish installation with Ansible method. Got the following error:

TASK [start docker-compose] ****************************************************
fatal: [root@1.2.3.4]: FAILED! => {“changed”: false, “msg”: “Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on vps.server.com’s Python /usr/bin/python. Please read module documentation and install in the appropriate location, for example via pip install docker or pip install docker-py (Python 2.6). The error was: No module named requests.exceptions”}

That final like sometimes vary to "no module named credentials"

Installed docker and docker-py with pip to no avail.

Tried adding:

[defaults]
 ansible_python_interpreter = /usr/bin/python2

Still no luck.

FWIW, I am getting this warning at the beginning:

TASK [setup] *******************************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 19.10 on host root@1.2.3.4 should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs .ansible.com/ansible/2.8/reference_appendices/interpreter_discovery.html for more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

I finalized the installation with just the docker method, but anyway leaving this here for it could be helpful.

**Comment by dessalines** [comment]
Did you try these two fixes? First google results:

- https://stackoverflow.com/questions/59384708/ansible-returns-with-failed-to-import-the-required-python-library-docker-sdk-f
- https://stackoverflow.com/questions/55373596/ansible-not-able-to-find-python-module/55993461
