### ISSUE TITLE
Bottom links and donations page (Branding)

### ISSUE THREAD

**Issue by cloned1** [dessalines/lemmy#616]
Hello.

Just set up a Lemmy instance and i like it so far. However there is something that doesn't seem to be customizable and that is the links at the bottom of the page, the donation page, and the "powered by" box visible from mobile. Since this is open and free software i totally understand the need to give credit where it is due and publicize the authors and donation methods. However, in terms of branding I think these elements take a slightly too prevalent space in the site, and a donation page could be needed by the admin of that instance as well. 

I wouldn't mind all that stuff present in my site but I'd like to have space for my own branding as well, hopefully with priority to my own branding. Is this workable?

**Comment by dessalines** [comment]
Your site sidebar, which you can put anything you like in (even instance donation links, or links to any pages, etc), will always be above that `powered by` section. Its full markdown, so it can even support images, or anything you like.

**Comment by cloned1** [comment]
Ok,  i get it. But what about the donations page?

**Comment by dessalines** [comment]
I'd like the donation link to stay at the bottom. If you want your own, instance donation page / link, you can put it in your site sidebar. Or link to a donation page from your site sidebar.

**Comment by Nutomic** [comment]
I think it makes sense to have two sections on the donation page, something like "donate to instance" and "donate to lemmy development".

**Comment by cloned1** [comment]
> I think it makes sense to have two sections on the donation page, something like "donate to instance" and "donate to lemmy development".

Of course that makes more sense. I am stopping using this app due to this critical shortcomming.

**Comment by dessalines** [comment]
> Of course that makes more sense. I am stopping using this app due to this critical shortcomming.

I've spent hundreds of hours on this, and your first few comments are telling me this app is unusable because I won't do work to build you a specific donation page?

**Comment by dessalines** [comment]
We can open this up as another ticket eventually if someone wants. Overall tho I want to minimize the amount of "custom sections" that a site has, and for now I don't see a reason to a second field outside of the `description` IE the Sidebar.
