### ISSUE TITLE
Browser notifications shown as plain HTML

### ISSUE THREAD

**Issue by Nutomic** [dessalines/lemmy#618]
I enabled browser notifications, and this is how they look.  Obviously not very nice.

Using Firefox 68.6.0esr, on Android 9.

![photo_2020-04-01_13-43-13](https://user-images.githubusercontent.com/1044450/78133699-6e78dc00-740e-11ea-8caa-4f9744ae354f.jpg)

**Comment by dessalines** [comment]
Hrm, damn I did a markdown to html converter which works for the popup, but not for the browser notifications unfortunately, looks like that notification body can only be a text string. I'll just leave it as markdown for that, since there's nothing else I can do.

**Comment by Nutomic** [comment]
It would also be nice to add an icon for the notification while you're at it, but maybe thats too complicated.

**Comment by dessalines** [comment]
It does have an icon, you might have to pull down that notification to see it. it uses the lemmy icon if the user doesn't have an avatar:

```
    let creator_avatar = reply.creator_avatar
      ? reply.creator_avatar
      : `${window.location.protocol}//${window.location.host}/static/assets/apple-touch-icon.png`;
```
