### ISSUE TITLE
Mod related bugs

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#68]
* the user who created the post can lock it, but cannot unlock it. A mod cannot unlock it either without refreshing the page. only after a mod has locked and then unlocked it
user can unlock a post that a mod locked
* mod actions do not work in firefox except unlocking, locking and appointing as mod
* older mod cannot remove newer mod from their /u/ page
* no cancel button under "remove community"
*not finding a way to resign as mod

**Comment by mister-monster** [comment]
If you need any elaboration or explanation on these issues feel free to ask.
