### ISSUE TITLE
Add a search page

### ISSUE THREAD

**Issue by dessalines** [dessalines/lemmy#70]

**Comment by zesterer** [comment]
If you're going to do this, please add filtering by forum, keywords, tags, users, etc.

```
Search: forum:veloren user:zesterer
```

**Comment by blakecallens** [comment]
Consider using [sonic](https://github.com/valeriansaliou/sonic) for this.

**Comment by dessalines** [comment]
Fixed by https://github.com/dessalines/lemmy/commit/73b9266580d23724e79983c49740546015ad74f8
