### ISSUE TITLE
Forum list does not update / Not fetching back all communities.

### ISSUE THREAD

**Issue by emilypi** [dessalines/lemmy#72]
I created the Haskell forum, which is featured on the "trending" front page, however when I go to make a test post it does not show up as an option:

<img width="639" alt="Screen Shot 2019-04-18 at 1 34 22 AM" src="https://user-images.githubusercontent.com/10459342/56338949-3a16fc00-617a-11e9-9582-c9d58636d494.png">

Is this intended? It seems like some information is not being propagated correctly.

**Comment by dessalines** [comment]
Ohhh yep this is a bug, introduced when I did paging communities.
