### ISSUE TITLE
Help Wanted?

### ISSUE THREAD

**Issue by bmcollier** [dessalines/lemmy#73]
Hi, I want to learn the stack you're using. I'm a fairly experienced coder. What's the best way to get involved? Just start making pull requests, or do you have a work stack you'd like someone to look at?

**Comment by dessalines** [comment]
Heck yeah, this will need all the help it can get.

I'd start familiarizing with the codebase, and PRs are very welcome.

As for something to focus on, I'd say usablity, bug-finding, adding features... def join the [matrix chat](https://matrix.to/#/!BZVTUuEiNmRcbFeLeI:matrix.org?via=matrix.org&via=disroot.org&via=decred.org) too. The federation is the thing I'm weakest on, I laid the groundwork for it but its not yet set up.

**Comment by ChrisCates** [comment]
@dessalines, what sort of deployment strategy do you intend to take with this?

Perhaps some sort of upstream with NGINX?

**Comment by dessalines** [comment]
The development server is using nginx with letsencrypt.

**Comment by ChrisCates** [comment]
@dessalines, that's good, nginx will be able to handle API and Front end servers no problem.

How are the logistics for your Postgres sharding, federation and so forth?

**Comment by dessalines** [comment]
I'm not sure what the question is. I doubt it'll be necessary to shard the DB ever, considering this will be federated, and its really not that much data. I don't even think mastodon does this.

**Comment by ChrisCates** [comment]
@dessalines, no worries.

**The question is:**  do you expect the developer to create their own Federated cluster when using PG. if not, what are the logistics for federation?

**Comment by dessalines** [comment]
When you run the docker, and create an instance, it sets up a postgres dB for you.

All data for a community is stored on that instance. 

Youd have to be more specific about what you mean by logistics.

**Comment by ChrisCates** [comment]
Oh my, talk about miscommunication.
So, I'm guessing we'd use Kuburnetes: https://docs.docker.com/docker-for-windows/kubernetes/?

I'm sorry, but, I have one last question, what was your intention in using the word "Federated" in the description?

**Comment by ChrisCates** [comment]
Oh my, well talk about some miscommunication here.
Thank you for taking the time to speak.
