### ISSUE TITLE
Why federated - option to disable moderation?

### ISSUE THREAD

**Issue by juliangaal** [dessalines/lemmy#75]
Could you go into the reason why you went fully federated? Why not optional? Thanks

**Comment by qazip** [comment]
What a weird question to ask. Imagine if e-mail was not federated, what a clusterfuck would that be. Google would probably be even more of a monopoly. 

Federation is the way to go.

**Comment by marek-lach** [comment]
Federation is awesome. It's the ability to see more content and for your content to be seen by more users, while being resilient to shut-downs. If what you want to do is to run a private instance, the solution is simply to disable user registrations. Not federation.

There are plenty of reddit alternatives that are not federated. They suffer from a lack of content and user engagement.

**Comment by juliangaal** [comment]
> What a weird question to ask. Imagine if e-mail was not federated, what a clusterfuck would that be. Google would probably be even more of a monopoly.
> 
> Federation is the way to go.

I did not ask for your opinion
