### ISSUE TITLE
UX: Purpose of the New comments sidebar 

### ISSUE THREAD

**Issue by erlend-sh** [dessalines/lemmy#98]
I’d like to hear from other Lemmy testers: What do you think of the  “New comments” sidebar

For me it’s overwhelming to be honest.

At first I didn’t understand what it was. New comments on the forum in general or specifically to this topic??? (To the topic, it seems)

And it’s double work; I gotta scan through a lot of posts I’ve already read.

Wouldn’t it be better to just give that space to the replies? That way deeply nested replies can go further before starting to go below max post width to fit on the page.

**Comment by mister-monster** [comment]
I think the reasoning is to keep the web interface as familiar to Reddit users as possible without building an exact clone replica of Reddit. @dessalines would I be correct in that assumption?

**Comment by dessalines** [comment]
I messed with it a little bit to make it fit to your viewport, and added a comment box over there too. It feels a little more like a chat now: https://dev.lemmy.ml/#/post/4

To answer your question, they're both just different views of the **exact same data**, one is just threaded and sortable (default sort hot), and the other is sorted by new to feel like a chat. You'll notice if you reply to one comment, even on the chat, it'll show up correctly where it should be in the thread.

I realize you're coming from a forum world, coming from reddit mostly I guess these would be called `threads`, IE, the comment section for a link that was posted. 

This is a huge problem / task that comes up alot with threaded convos vs non-threaded chats: one is better for seeing new info, the other for seeing important / upvoted info. 

Its impossible to do both at the same time, IE, to show both comments by time, by thread ...  so I figured I'd do it in two panes. 

Here's a good thread about this w/ regards to riot. https://github.com/vector-im/riot-web/issues/2349

On smaller screens that chat section is actually hidden.

**Comment by mister-monster** [comment]
I think if this UI choice isn't working out a good use of the space would be top posts within the community i.e. if you're on a post in c/rust, the panel would show you top however many posts from c/rust. Just a thought, the space could be used for virtually anything and is specific to the web UI only.
